### ISSUE TITLE
crash occures when dismmising compose page of RequestList.

### ISSUE THREAD

**Issue by DominatorVbN** [zendesk/zendesk_sdk_ios#491] opened 2019-02-27 06:08 UTC
- SDK version: 2.3.1
- Xcode version:10.1
- iOS or Simulator:iPhone 6
- iOS Version:12.1
- Swift version:4

Steps to Reproduce:

1. just push RequestUi.buildRequestList() and goto compose,
2.tap the cross button

Error Log:erminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <ZendeskSDK.ProgressBar 0x10fd86a40> for the key path "self.bounds" from <UINavigationBar 0x10fd2bda0> because it is not registered as an observer.'
*** First throw call stack:
(0x21995bef8 0x218b29a40 0x219860ac4 0x21a325254 0x21a325008 0x10203cbcc 0x101fb83d4 0x101fb8344 0x101fb8594 0x2461a2ba0 0x2461a32d8 0x2461a4808 0x246bed120 0x246bebc30 0x246beb8ac 0x101ef7330 0x101ef77f0 0x101fdc110 0x101fdc83c 0x101fdb2ec 0x101f6b7b0 0x101f6c150 0x101f6bec0 0x101a83bf4 0x101a83c20 0x101563f04 0x101a83830 0x101f6bdac 0x101f6bf74 0x101fdb1f4 0x101fdb34c 0x2461a2b40 0x246100200 0x2461a2b40 0x2460d537c 0x2461a2b40 0x2461a34c0 0x2460c5230 0x2460ce4f0 0x2460c9424 0x2461c7204 0x246bc3288 0x246bc2f20 0x246bc5030 0x246bcd490 0x246bcda7c 0x246bcdb1c 0x21df4f394 0x103e00de4 0x103e0ea94 0x2198ea1bc 0x2198e5084 0x2198e45b8 0x21bb58584 0x246760bc8 0x100a5b4a4 0x2193a4b94)

**Comment by RonanMcH** [comment] 2019-03-05 10:30
HI @DominatorVbN ,
I wasn't able to reproduce this issue. I wasn't able to test on the specific device (iPhone 6, iOS 12.1) but I tested it on that simulator and some other 12.1 devices.
Does it happen on the iPhone 6 iOS 12.1 simulator for you? Does it happen on any other iOS versions or devices?
The observer for "self.bounds" is registered on `viewDidLoad` of the `compose` screen so it is strange that it is not there. Can you send us the exact code you are using to push it?
Thanks,
Ronan.

**Comment by DominatorVbN** [comment] 2019-03-05 12:07
func getAllMyTicket(){
        let config = RequestUiConfiguration()
        let requestListController = RequestUi.buildRequestList(with: [config])
        self.navigationController?.pushViewController(requestListController, animated: true)
    }

this is the code i am using.

**Comment by DominatorVbN** [comment] 2019-03-05 12:09
the list opens correctly but when I click on create a ticket -> then on the cross it gets crashed.

**Comment by DominatorVbN** [comment] 2019-03-05 12:13
![query](https://user-images.githubusercontent.com/41822551/53804666-261e8e80-3f6e-11e9-9907-9f98274f8152.gif)

**Comment by RonanMcH** [comment] 2019-03-05 13:26
Hi @DominatorVbN ,
which specific devices can you reproduce this on? Is it only on iOS 12? Does it happen on simulator? 
Thanks,
Ronan.

**Comment by DominatorVbN** [comment] 2019-03-05 13:28
no, it's happening in real device iPhone 6
exactly

**Comment by DominatorVbN** [comment] 2019-03-05 13:31
![query](https://user-images.githubusercontent.com/41822551/53808771-19536800-3f79-11e9-9ed3-f909eab32b45.jpg)

**Comment by alena-k** [comment] 2019-03-06 11:24
Hi @DominatorVbN,

We couldn't reproduce the problem.
Could you possibly provide a sample app that would reproduce the crash?
Or could you tell us more about your View Controller stack, so that we could recreate it?

Thanks,
Alena.

**Comment by DominatorVbN** [comment] 2019-03-07 06:55
Architechure:
TabBarController -> CustomNavigationController -> ViewController -> StackView -> Buttons(-> action [push RequestUi.buildRequestList(with: [config])]) , tableView

Error stack:
2019-03-07 12:23:20.079515+0530 CFSS[7705:53232] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <ZendeskSDK.ProgressBar 0x7f889ec26ce0> for the key path "self.bounds" from <UINavigationBar 0x7f889ed15670> because it is not registered as an observer.'

*** First throw call stack:

(

	0   CoreFoundation                      0x00000001062301bb __exceptionPreprocess + 331

	1   libobjc.A.dylib                     0x0000000104da6735 objc_exception_throw + 48

	2   CoreFoundation                      0x0000000106230015 +[NSException raise:format:] + 197

	3   Foundation                          0x0000000103751214 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 488

	4   Foundation                          0x000000010375169b -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84

	5   ZendeskSDK                          0x0000000104958a33 $S10ZendeskSDK11ProgressBarC6removeyyF + 227

	6   ZendeskSDK                          0x00000001048c7add $S10ZendeskSDK25RequestListViewControllerC17removeProgressBaryyF + 125

	7   ZendeskSDK                          0x00000001048c7a46 $S10ZendeskSDK25RequestListViewControllerC17viewWillDisappearyySbF + 118

	8   ZendeskSDK                          0x00000001048c7ce3 $S10ZendeskSDK25RequestListViewControllerC17viewWillDisappearyySbFTo + 51

	9   UIKitCore                           0x000000010f9855b5 -[UIViewController _setViewAppearState:isAnimating:] + 1060

	10  UIKitCore                           0x000000010f985d4c -[UIViewController __viewWillDisappear:] + 95

	11  UIKitCore                           0x000000010f9873ed -[UIViewController viewWillMoveToWindow:] + 696

	12  UIKitCore                           0x00000001104708de -[UIView(Hierarchy) _willMoveToWindow:] + 472

	13  UIKitCore                           0x000000011046f347 __UIViewWillBeRemovedFromSuperview + 474

	14  UIKitCore                           0x000000011046efbc -[UIView(Hierarchy) removeFromSuperview] + 95

	15  ZendeskSDK                          0x00000001047f64c9 $S10ZendeskSDK23ContainerViewControllerC06activeE0So06UIViewE0CSgvW + 777

	16  ZendeskSDK                          0x00000001047f69f0 $S10ZendeskSDK23ContainerViewControllerC06activeE0So06UIViewE0CSgvs + 288

	17  ZendeskSDK                          0x00000001048ed97d $S10ZendeskSDK26CoordinatingViewControllerC7present33_F3BD73B941AFC4700187B3C331E1F0E0LL04viewE0yAA14ContainerChild_So06UIViewE0CXc_tF + 93

	18  ZendeskSDK                          0x00000001048edfcc $STA + 28

	19  ZendeskSDK                          0x00000001048ec9f2 $S10ZendeskSDK14ContainerChild_So16UIViewControllerCXcIegg_AaB_ADXcIeyBy_TR + 66

	20  ZendeskSDK                          0x00000001048769c9 $S10ZendeskSDK14ContainerChild_So16UIViewControllerCXcIeyBy_AaB_ADXcIegg_TR + 25

	21  ZendeskSDK                          0x000000010487820d $S10ZendeskSDK14ContainerChild_So16UIViewControllerCXcIeyBy_AaB_ADXcIegg_TRTA + 13

	22  ZendeskSDK                          0x0000000104877307 $S10ZendeskSDK18RequestCoordinatorC5route33_135C3D6137F8056E02FF5E9F7E3B21BELL8settings7present4withy0a8ProviderB021ConversationsSettingsCSg_yAA14ContainerChild_So16UIViewControllerCXccAA0vwY8Delegate_ptF + 471

	23  ZendeskSDK                          0x000000010487705b $S10ZendeskSDK18RequestCoordinatorC5start7present4withyyAA14ContainerChild_So16UIViewControllerCXcc_AA0hiK8Delegate_ptFy0a8ProviderB021ConversationsSettingsCSgcfU_ + 267

	24  ZendeskSDK                          0x0000000104878199 $S10ZendeskSDK18RequestCoordinatorC5start7present4withyyAA14ContainerChild_So16UIViewControllerCXcc_AA0hiK8Delegate_ptFy0a8ProviderB021ConversationsSettingsCSgcfU_TA + 25

	25  ZendeskProviderSDK                  0x0000000104699630 $S18ZendeskProviderSDK024ZDKConversationsSettingsB0C016getConversationsE08callbackyyAA0gE0CSgc_tFZyAGcfU_TA + 32

	26  ZendeskProviderSDK                  0x0000000104699664 $S18ZendeskProviderSDK21ConversationsSettingsCIegg_ACIegn_TRTA + 20

	27  ZendeskCoreSDK                      0x00000001044fe5ec $S14ZendeskCoreSDK16SettingsProviderV03getD0_8callbackyxm_y11DefaultTypeQzctAA09DecodableH0RzlF + 2140

	28  ZendeskProviderSDK                  0x0000000104699238 $S18ZendeskProviderSDK024ZDKConversationsSettingsB0C016getConversationsE08callbackyyAA0gE0CSgc_tFZTf4nd_n + 376

	29  ZendeskProviderSDK                  0x0000000104698e59 $S18ZendeskProviderSDK024ZDKConversationsSettingsB0C016getConversationsE08callbackyyAA0gE0CSgc_tFZ + 9

	30  ZendeskSDK                          0x0000000104876f2f $S10ZendeskSDK18RequestCoordinatorC5start7present4withyyAA14ContainerChild_So16UIViewControllerCXcc_AA0hiK8Delegate_ptF + 303

	31  ZendeskSDK                          0x0000000104877107 $S10ZendeskSDK18RequestCoordinatorC5start7present4withyyAA14ContainerChild_So16UIViewControllerCXcc_AA0hiK8Delegate_ptFTo + 135

	32  ZendeskSDK                          0x00000001048ec91c $S10ZendeskSDK26CoordinatingViewControllerC13viewDidAppearyySbF + 300

	33  ZendeskSDK                          0x00000001048eca43 $S10ZendeskSDK26CoordinatingViewControllerC13viewDidAppearyySbFTo + 51

	34  UIKitCore                           0x000000010f985544 -[UIViewController _setViewAppearState:isAnimating:] + 947

	35  UIKitCore                           0x000000010f8d4c28 -[UINavigationController viewDidAppear:] + 187

	36  UIKitCore                           0x000000010f985544 -[UIViewController _setViewAppearState:isAnimating:] + 947

	37  UIKitCore                           0x000000010f8a77d9 -[UITabBarController viewDidAppear:] + 112

	38  UIKitCore                           0x000000010f985544 -[UIViewController _setViewAppearState:isAnimating:] + 947

	39  UIKitCore                           0x000000010f985ef5 -[UIViewController _endAppearanceTransition:] + 197

	40  UIKitCore                           0x000000010f896a8b -[UIPresentationController transitionDidFinish:] + 879

	41  UIKitCore                           0x000000010f8a0149 -[_UICurrentContextPresentationController transitionDidFinish:] + 41

	42  UIKitCore                           0x000000010f89aef2 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.440 + 183

	43  UIKitCore                           0x000000010f9abc39 -[_UIViewControllerTransitionContext completeTransition:] + 102

	44  UIKitCore                           0x00000001104436a6 -[UITransitionView notifyDidCompleteTransition:] + 251

	45  UIKitCore                           0x000000011044331d -[UITransitionView _didCompleteTransition:] + 1383

	46  UIKitCore                           0x0000000110445910 -[UITransitionView _transitionDidStop:finished:] + 104

	47  UIKitCore                           0x000000011044e34d -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 343

	48  UIKitCore                           0x000000011044e98d -[UIViewAnimationState animationDidStop:finished:] + 293

	49  UIKitCore                           0x000000011044ea41 -[UIViewAnimationState animationDidStop:finished:] + 473

	50  QuartzCore                          0x0000000107337cad _ZN2CA5Layer23run_animation_callbacksEPv + 323

	51  libdispatch.dylib                   0x0000000108c39602 _dispatch_client_callout + 8

	52  libdispatch.dylib                   0x0000000108c4699a _dispatch_main_queue_callback_4CF + 1541

	53  CoreFoundation                      0x00000001061953e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9

	54  CoreFoundation                      0x000000010618fa76 __CFRunLoopRun + 2342

	55  CoreFoundation                      0x000000010618ee11 CFRunLoopRunSpecific + 625

	56  GraphicsServices                    0x000000010d6b01dd GSEventRunModal + 62

	57  UIKitCore                           0x000000010ff9e81d UIApplicationMain + 140

	58  CFSS                                0x0000000102c20a77 main + 71

	59  libdyld.dylib                       0x0000000108caf575 start + 1

	60  ???                                 0x0000000000000001 0x0 + 1

)

libc++abi.dylib: terminating with uncaught exception of type NSException

(lldb)

**Comment by RonanMcH** [comment] 2019-03-20 16:09
Hi @DominatorVbN ,
I believe that the issue is with the particular nav stack you have and possibly with your custom `navigationController`.  We call: 
```
        if let navBar = self.navigationController?.navigationBar {
            view.addObserver(self, forKeyPath: "self.bounds", options: [.new, .old], context: nil)
        }
``` 
in the `viewWillAppear` of the `requestListController` but we don't have the same `if let` guarding for removing this observer which is where the crash is happening. It is clear that either a `navBar` isn't being detected or `viewWillAppear` isn't being called.

If you could send us a sample project that would reproduce this issue, we could debug exactly what is going on.
Thanks,
Ronan.

**Comment by HamstringAssassin** [comment] 2019-04-03 09:40
Hi @DominatorVbN,

Just wondering if you've had any luck with this issue? if not, send us on a sample app and we'll be happy to debug it some more. 

Otherwise, one of my colleagues might close this issue in the coming days. 

Cheers,
Al

**Comment by RonanMcH** [comment] 2019-04-16 13:49
Hi @DominatorVbN , 
I am gonna tentatively close this issue due to inactivity. Please feel free to reopen if the issue persists.
Thanks,
Ronan.

**Closed by RonanMcH** 2019-04-16 13:49 UTC
Labels: pending information
