### ISSUE TITLE
Showing a single article by pushing an article view controller doesn't render the article the first time

### ISSUE THREAD

**Issue by jeffremer** [zendesk/zendesk_sdk_ios#390] opened 2018-05-23 23:35 UTC
When you create a view controller for a single article the very first time, push it onto the navigation stack the article view controller appears to try to render off screen. If you go back and then try to view the article again it renders properly. You can see an activity indicator off in the corner of the screen.

- SDK version: 2.0.3
- Xcode version: 9.3.1
- iOS or Simulator: iPhone 8 Simulator
- iOS Version: 11.3
- Swift version: 4.1

Steps to Reproduce:

1. Create a article view controller for an article you haven't seen before
2. Push the article view controller via `-[UINavigationController pushViewController:animated:]`

Here's an animated gif showing the off-screen rendering:

![Offscreen](http://g.recordit.co/dJuCwRjsC7.gif)

I did this in [this sample app](https://github.com/jeffremer/ZendeskWarning), this is the entirety of the code (account details redacted), however it happens in our production app as well.

```obj-c
#import "ViewController.h"

@import ZendeskCoreSDK;
@import ZendeskSDK;

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad
{
    [ZDKZendesk initializeWithAppId:@"appID" clientId:@"secret" zendeskUrl:@"https://support.strava.com"];
    [ZDKSupport initializeWithZendesk:[ZDKZendesk instance]];
    id<ZDKObjCIdentity> userIdentity = [[ZDKObjCAnonymous alloc] initWithName:nil email:nil];
    [[ZDKZendesk instance] setIdentity:userIdentity];
}

- (IBAction)showArticle:(id)sender
{
    UIViewController *articleController = [ZDKHelpCenterUi buildHelpCenterArticleWithArticleId:@"216919427"
                                                                                    andConfigs:@[]];
    [self.navigationController pushViewController:articleController animated:YES];
}

@end
```

**Comment by jeffremer** [comment] 2018-05-25 17:00
It's been two days and this issue has not been acknowledged. Seems like a pretty fundamental part of this SDK is broken.

**Comment by baz8080** [comment] 2018-05-28 09:42
Hi Jeff,

Sorry for the lateness. We (the devs) do a rotating support duty (Android, iOS...), and this has been confounded by a lot of the developers being at conferences and / or travelling. We'll try to debug this for you this week.

**Comment by surjeetsg** [comment] 2018-05-29 10:10
I am also facing this issue with latest version of sdk.

**Comment by KillianSmith0** [comment] 2018-05-29 10:43
Hi @surjeetsg, we are currently looking into this.. Can you confirm how you replicated the issue?
Eg. From above:
SDK version: 2.0.3
Xcode version: 9.3.1
iOS or Simulator: iPhone 8 Simulator
iOS Version: 11.3
Swift version: 4.1

Thanks

**Comment by surjeetsg** [comment] 2018-05-29 11:26
Hello KillianSmith0,

SDK version: 2.0.3
Xcode version: 9.3.1
iOS or Simulator: iPhone 8 Simulator / iPhone 8 / iPhoneX
iOS Version: 11.3
Swift version: 4.1
 
I did same steps as mentioned by @jeffremer, and face this issue. This issue is random and could not reproduce each time, But mostly occurs when launch app and open first article.

**Comment by KillianSmith0** [comment] 2018-05-29 11:55
Thanks @surjeetsg for getting back, I also found this to be random, therefore it's quite awkward to debug. I'll keep looking into the issue and get back to this post when I have an update

**Comment by jeffremer** [comment] 2018-05-29 15:04
> I also found this to be random

@KillianSmith0 - it seems to be pretty easily reproducible if you look at the article right after freshly installing the app. Give this a try: 

1. Delete the app from the simulator
2. Run
3. Try to view the article

With the [sample app that I linked](https://github.com/jeffremer/ZendeskWarning) I can reproduce it 100% of the time repeating those steps.

**Comment by KillianSmith0** [comment] 2018-05-29 21:08
@jeffremer - I was able to replicate with your sample app but will have to change the setup of our dev env to further debug the problem. As I am the only iOS dev available at the moment, there is a number of issue I've had to attend to. I'll make this a priority tomorrow and hopefully have an answer for you by the end of the week. Sorry about the delay

**Comment by KillianSmith0** [comment] 2018-06-01 11:16
@jeffremer, @surjeetsg - apologies for the delay on this issue, as mentioned above we are down a few bodies at the moment. I've pinned down the exact problem with the issue and currently working on the fix. We have a patch release coming shortly, and the fix will be included. Sorry for any inconvenience.

**Comment by shamikumar** [comment] 2018-06-04 04:51
@KillianSmith0 Please update here, Once you guys release a patch with this fix.

**Comment by surjeetsg** [comment] 2018-06-04 04:52
@KillianSmith0 Please update here, Once you guys release a patch with this fix.

**Closed** 2018-07-03 14:34 UTC
Labels: bug, pending release

**Comment by camanjj** [comment] 2018-07-17 20:38
@KillianSmith0 I am also getting this issue even after updating the Zendesk SDK to 2.0.5. The effects are similar to the others. It randomly occurs when pushing an article and only on first load of an article. Any insight or help?

**Comment by jeffremer** [comment] 2018-08-07 21:08
This is still reproducible in 2.0.5 for us as well. Please reopen this issue.

**Comment by KillianSmith0** [comment] 2018-08-08 08:18
@camanjj, @jeffremer - this issue should be resolved in our most recent release v2.1.0. Can you update accordingly, and let me know if the issue persists? Thanks

**Comment by jeffremer** [comment] 2018-08-08 17:59
Thanks, yes, looks good so far in 2.1.0.

**Comment by jeffremer** [comment] 2018-09-18 00:43
@KillianSmith0 this is _still_ happening, or happening again, and it's easily reproducible in our app. The first time you go to an article it doesn't appear. It'll get the title but the rest of the screen will be blank.
