### ISSUE TITLE
Help Center keeps submitting tickets under old identity after being given an new identity

### ISSUE THREAD

**Issue by blagh** [zendesk/zendesk_sdk_ios#295] opened 2017-05-24 20:56 UTC
- SDK version: 1.9.2.2
- Xcode version: 8.3.2
- iOS or Simulator: simulator
- iOS Version: any
- Swift version: 3.1

Steps to Reproduce:
1. Login to app
2. Open the help center as below, and submit a ticket through the UI:

        let identity = ZDKAnonymousIdentity()
        if let accountInfo = getAccountInfo() {
            identity.email = accountInfo.email
            identity.name = accountInfo.businessName
        }
        ZDKConfig.instance().userIdentity = identity

        let helpCenter = ZDKHelpCenterOverviewContentModel.defaultContent()
        ZDKHelpCenter.pushOverview(nav, with: helpCenter) 

3. Logout of app, and login to a different account (without restarting the app)
4. Submit a second ticket through the same code paths
5. Go to the Zendesk dashboard and observe the resulting tickets

Expected:
First ticket is under first account, second ticket under second account

Actual:
Both tickets are under first account.

**Comment by tecknut** [comment] 2017-05-25 10:15
Hey @blagh can you provide some logs of the issue going through the repro steps you've outlined?

**Comment by tecknut** [comment] 2017-05-25 10:16
Additionally, could you log the values of `accountInfo` each time around to verify they are changing?

**Comment by blagh** [comment] 2017-05-25 15:10
Can do!

**Comment by blagh** [comment] 2017-05-25 16:05
Gif of repro:

<img src="https://cloud.githubusercontent.com/assets/5570885/26458687/f90d606e-4141-11e7-9164-8ba8e2c30b3e.gif" width=200px>

Modified snippet:

    print("Setting up ZDKAnonymousIdentity")
    let identity = ZDKAnonymousIdentity()
    if let accountInfo = getAccountInfo() {
        identity.email = accountInfo.email
        print("Identity email: \(accountInfo.email)")
        identity.name = accountInfo.businessName
        print("Identity name: \(accountInfo.businessName)")
    }
    ZDKConfig.instance().userIdentity = identity

    print("Opening Help Center")
    let helpCenter = ZDKHelpCenterOverviewContentModel.defaultContent()
    ZDKHelpCenter.pushOverview(nav, with: helpCenter)


Relevant logs:

    transitioning from loggedOut to loggingIn
    transitioning from loggingIn to authenticated

    ....

    Setting up ZDKAnonymousIdentity
    Identity email: Optional("abcdefghi@freshenv.com")
    Identity name: ¯\_(ツ)_/¯
    Opening Help Center

    ....

    transitioning from loggedIn to loggedOut

    ....

    transitioning from loggedOut to loggingIn
    transitioning from loggingIn to authenticated

    ....

    Setting up ZDKAnonymousIdentity
    Identity email: Optional("someother@freshenv.com")
    Identity name: very great company
    Opening Help Center

But both emails show up under `abcdefghi@freshenv.com`:

<img src="https://cloud.githubusercontent.com/assets/5570885/26458499/6ee10030-4141-11e7-9cd2-58b1990b7951.png" width=200px> <img src="https://cloud.githubusercontent.com/assets/5570885/26458503/722bb69a-4141-11e7-8902-b751d2ba82d1.png" width=200px>

**Comment by blagh** [comment] 2017-05-25 16:10
I tried unwrapping the optional value, but this also didn't seem to help.

**Comment by tecknut** [comment] 2017-05-25 18:37
Ok great, thanks for the extra details. Could you enable the logging in the SDK? This will add much more logs and should shine some light on whether the new identity is going out with the network requests.

Look for `ZDKLogger` it has an enable function. 

Thanks

**Comment by blagh** [comment] 2017-05-26 15:07
Here is the snippet for sending the first ticket:

```transitioning from loggedOut to loggingIn
transitioning from loggingIn to authenticated
transitioning from authenticated to initialSync

Setting up ZDKAnonymousIdentity
Identity email: Optional("abcdefghi@freshenv.com")
Identity name: Optional("¯\\_(ツ)_/¯")
Opening Help Center
2017-05-26 11:00:21.834 FreshBooks[31878:698800] [DEBUG]: No SDK configuration file found in local storage, sending request to fetch configuration file.
2017-05-26 11:00:21.835 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:21.836 FreshBooks[31878:698800] [DEBUG]: About to execute [0x600000209030]: https://freshbooks1495119909.zendesk.com/api/mobile/sdk/settings/5cea52dd1635a5b63fe452d1f74796d8a1453bbf447e0899.json
with headers
{
    Accept = "application/json";
    "Accept-Language" = en;
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "D8F7274D-3A93-494A-9CDC-443CB92965AB";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:21.900 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKHelpCenter.helpCenterOverview.title" = "Help";
2017-05-26 11:00:21.951 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:21.951 FreshBooks[31878:698800] [DEBUG]: No SDK configuration file found in local storage, sending request to fetch configuration file.
2017-05-26 11:00:21.951 FreshBooks[31878:698800] [DEBUG]: Request to fetch settings was queued, block will be called when setting is fetched
2017-05-26 11:00:22.128 FreshBooks[31878:698800] [DEBUG]: Response code [0x600000209030]: 200
2017-05-26 11:00:22.128 FreshBooks[31878:698800] [DEBUG]: Request success: [0x600000209030]: https://freshbooks1495119909.zendesk.com/api/mobile/sdk/settings/5cea52dd1635a5b63fe452d1f74796d8a1453bbf447e0899.json
2017-05-26 11:00:22.130 FreshBooks[31878:698800] [DEBUG]: No support for en, Help Center is enabled in your application settings
2017-05-26 11:00:22.131 FreshBooks[31878:698800] [DEBUG]: Successfully updated SDK settings
2017-05-26 11:00:22.133 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.rightBarButton.title.contact" = "Contact us";
2017-05-26 11:00:22.139 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:22.139 FreshBooks[31878:698800] [DEBUG]: Adding request to pending queue.
2017-05-26 11:00:22.140 FreshBooks[31878:698800] [DEBUG]: About to execute login request [0x6080002136b0]: https://freshbooks1495119909.zendesk.com/access/sdk/anonymous
with headers
{
    Accept = "application/json";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "D8F7274D-3A93-494A-9CDC-443CB92965AB";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:22.140 FreshBooks[31878:698800] [DEBUG]: About to execute [0x608000213740]: https://freshbooks1495119909.zendesk.com/access/sdk/anonymous
with headers
{
    Accept = "application/json";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "D8F7274D-3A93-494A-9CDC-443CB92965AB";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:22.452 FreshBooks[31878:698800] [DEBUG]: Response code [0x608000213740]: 200
2017-05-26 11:00:22.453 FreshBooks[31878:698800] [DEBUG]: Request success: [0x608000213740]: https://freshbooks1495119909.zendesk.com/access/sdk/anonymous
2017-05-26 11:00:22.453 FreshBooks[31878:698800] [DEBUG]: Login request success [0x6080002136b0]: https://freshbooks1495119909.zendesk.com/access/sdk/anonymous
2017-05-26 11:00:22.454 FreshBooks[31878:698800] [DEBUG]: Executing queued requests after login.
2017-05-26 11:00:22.454 FreshBooks[31878:698800] [DEBUG]: Adding auth to request [0x6000002096e0]: https://freshbooks1495119909.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
2017-05-26 11:00:22.454 FreshBooks[31878:698800] [DEBUG]: About to execute [0x600000209090]: https://freshbooks1495119909.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 3d456ebd7507b46cbef7e501c087f3824bd15472c9effe34e4444b0a94bed5b0";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "D8F7274D-3A93-494A-9CDC-443CB92965AB";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:22.834 FreshBooks[31878:698800] [DEBUG]: Response code [0x600000209090]: 200
2017-05-26 11:00:22.835 FreshBooks[31878:698800] [DEBUG]: Request success: [0x600000209090]: https://freshbooks1495119909.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
2017-05-26 11:00:22.838699-0400 FreshBooks[31878:698800] [LayoutConstraints] Custom views and layout for UITableViewHeaderFooterView should be contained within the content view. Offending view: <ZDKHelpCenterOverviewHeaderView: 0x7fef69c8de30; baseClass = UITableViewHeaderFooterView; frame = (0 0; 600 44); text = ''; opaque = NO; autoresize = W+H; layer = <CALayer: 0x600000625140>>
2017-05-26 11:00:23.727 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.requestList.title" = "My tickets";
2017-05-26 11:00:23.730 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.rightBarButton.title.new" = "New";
2017-05-26 11:00:24.247 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:24.248 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:00:24.249 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:00:24.251 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:24.251 FreshBooks[31878:698800] [WARNING]: -[ZDKRequestProvider getAnonymousRequestsWithTokens:byStatus:withCallack:]_block_invoke There are no requests to fetch
2017-05-26 11:00:24.253 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.requestList.empty" = "No tickets currently open";
2017-05-26 11:00:24.944 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.cancel.button" = "Cancel";
2017-05-26 11:00:24.944 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.submit.button" = "Send";
2017-05-26 11:00:24.946 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.title" = "Contact us";
2017-05-26 11:00:24.947 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.description.placeholder" = "Description";
2017-05-26 11:00:24.951 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.email.placeholder" = "Your email address";
2017-05-26 11:00:25.476 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:00:28.341507-0400 FreshBooks[31878:699448] 0x608000548610 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x608000548610> { count = 1, transaction: 0, voucher = 0x0, contents =
  "Result" => <int64: 0x608000838200>: 29
}
2017-05-26 11:00:28.343329-0400 FreshBooks[31878:699448] 0x600000145750 Daemon configuration query reply: XPC_TYPE_DICTIONARY  <dictionary: 0x600000145750> { count = 2, transaction: 0, voucher = 0x0, contents =
  "Dictionary" => <dictionary: 0x60000014c760> { count = 1, transaction: 0, voucher = 0x0, contents =
    "ServerURL" => <dictionary: 0x60000014b0b0> { count = 3, transaction: 0, voucher = 0x0, contents =
      "com.apple.CFURL.magic" => <uuid: 0x600000a530b0> C3853DCC-9776-4114-B6C1-FD9F51944A6D
      "com.apple.CFURL.string" => <string: 0x600000a52cc0> { length = 30, contents = "https://mesu.apple.com/assets/" }
      "com.apple.CFURL.base" => <null: 0x10e9c7f40>: null-object
    }
  }
  "Result" => <int64: 0x600000637ba0>: 0
}
2017-05-26 11:00:28.343823-0400 FreshBooks[31878:699448] [MobileAssetError:29] Unable to copy asset information from https://mesu.apple.com/assets/ for asset type com.apple.MobileAsset.TextInput.SpellChecker
2017-05-26 11:00:34.750 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.requestSubject" = "App ticket";
2017-05-26 11:00:34.751 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:34.751 FreshBooks[31878:698800] [DEBUG]: Attachments uploaded, sending request
2017-05-26 11:00:34.755 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:34.755 FreshBooks[31878:698800] [DEBUG]: Adding auth to request [0x60000020ae20]: https://freshbooks1495119909.zendesk.com/api/mobile/requests.json
2017-05-26 11:00:34.756 FreshBooks[31878:698800] [DEBUG]: About to execute [0x60000020c2b0]: https://freshbooks1495119909.zendesk.com/api/mobile/requests.json
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 3d456ebd7507b46cbef7e501c087f3824bd15472c9effe34e4444b0a94bed5b0";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "D8F7274D-3A93-494A-9CDC-443CB92965AB";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:35.344 FreshBooks[31878:698800] [DEBUG]: Response code [0x60000020c2b0]: 201
2017-05-26 11:00:35.345 FreshBooks[31878:698800] [DEBUG]: Request success: [0x60000020c2b0]: https://freshbooks1495119909.zendesk.com/api/mobile/requests.json
2017-05-26 11:00:35.874 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:35.875 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:00:35.876 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:00:35.877 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:35.877 FreshBooks[31878:698800] [DEBUG]: Adding auth to request [0x6080002147b0]: https://freshbooks1495119909.zendesk.com/api/mobile/requests/show_many.json?tokens=zjpAB5xchXHveYH4LtYiGmxAS&include=public_updated_at&status=new,open,pending,hold,solved&sort_by=updated_at&sort_order=desc
2017-05-26 11:00:35.877 FreshBooks[31878:698800] [DEBUG]: About to execute [0x608000215650]: https://freshbooks1495119909.zendesk.com/api/mobile/requests/show_many.json?tokens=zjpAB5xchXHveYH4LtYiGmxAS&include=public_updated_at&status=new,open,pending,hold,solved&sort_by=updated_at&sort_order=desc
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 3d456ebd7507b46cbef7e501c087f3824bd15472c9effe34e4444b0a94bed5b0";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "D8F7274D-3A93-494A-9CDC-443CB92965AB";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:36.280 FreshBooks[31878:698800] [DEBUG]: Response code [0x608000215650]: 200
2017-05-26 11:00:36.281 FreshBooks[31878:698800] [DEBUG]: Request success: [0x608000215650]: https://freshbooks1495119909.zendesk.com/api/mobile/requests/
```

And for the second ticket:

```
transitioning from loggedOut to loggingIn
transitioning from loggingIn to authenticated

Setting up ZDKAnonymousIdentity
Identity email: Optional("someother@freshenv.com")
Identity name: Optional("very great company")
Opening Help Center
2017-05-26 11:00:59.848 FreshBooks[31878:698800] [DEBUG]: No SDK configuration file found in local storage, sending request to fetch configuration file.
2017-05-26 11:00:59.849 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:59.849 FreshBooks[31878:698800] [DEBUG]: About to execute [0x600000203670]: https://freshbooks1495119909.zendesk.com/api/mobile/sdk/settings/5cea52dd1635a5b63fe452d1f74796d8a1453bbf447e0899.json
with headers
{
    Accept = "application/json";
    "Accept-Language" = en;
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "A7995028-9018-42E7-9FB5-E69D306C4C89";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:00:59.864 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKHelpCenter.helpCenterOverview.title" = "Help";
2017-05-26 11:00:59.874 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:59.875 FreshBooks[31878:698800] [DEBUG]: No SDK configuration file found in local storage, sending request to fetch configuration file.
2017-05-26 11:00:59.875 FreshBooks[31878:698800] [DEBUG]: Response code [0x600000203670]: 200
2017-05-26 11:00:59.884 FreshBooks[31878:698800] [DEBUG]: Request success: [0x600000203670]: https://freshbooks1495119909.zendesk.com/api/mobile/sdk/settings/5cea52dd1635a5b63fe452d1f74796d8a1453bbf447e0899.json
2017-05-26 11:00:59.886 FreshBooks[31878:698800] [DEBUG]: No support for en, Help Center is enabled in your application settings
2017-05-26 11:00:59.886 FreshBooks[31878:698800] [DEBUG]: Successfully updated SDK settings
2017-05-26 11:00:59.887 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.rightBarButton.title.contact" = "Contact us";
2017-05-26 11:00:59.890 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:00:59.890 FreshBooks[31878:698800] [DEBUG]: Adding auth to request [0x60800020ce30]: https://freshbooks1495119909.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
2017-05-26 11:00:59.890 FreshBooks[31878:698800] [DEBUG]: About to execute [0x608000211e60]: https://freshbooks1495119909.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 3d456ebd7507b46cbef7e501c087f3824bd15472c9effe34e4444b0a94bed5b0";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "A7995028-9018-42E7-9FB5-E69D306C4C89";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:01:00.217 FreshBooks[31878:698800] [DEBUG]: Response code [0x608000211e60]: 200
2017-05-26 11:01:00.217 FreshBooks[31878:698800] [DEBUG]: Request success: [0x608000211e60]: https://freshbooks1495119909.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
2017-05-26 11:01:00.938 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.requestList.title" = "My tickets";
2017-05-26 11:01:00.940 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.rightBarButton.title.new" = "New";
2017-05-26 11:01:01.455 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:01:01.455 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:01:01.456 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:01:01.457 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:01:01.457 FreshBooks[31878:698800] [WARNING]: -[ZDKRequestProvider getAnonymousRequestsWithTokens:byStatus:withCallack:]_block_invoke There are no requests to fetch
2017-05-26 11:01:01.459 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.requestList.empty" = "No tickets currently open";
2017-05-26 11:01:02.512 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.cancel.button" = "Cancel";
2017-05-26 11:01:02.513 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.submit.button" = "Send";
2017-05-26 11:01:02.515 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.title" = "Contact us";
2017-05-26 11:01:02.516 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.description.placeholder" = "Description";
2017-05-26 11:01:02.518 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.email.placeholder" = "Your email address";
2017-05-26 11:01:03.037 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:01:14.375 FreshBooks[31878:698800] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.requestSubject" = "App ticket";
2017-05-26 11:01:14.376 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:01:14.377 FreshBooks[31878:698800] [DEBUG]: Attachments uploaded, sending request
2017-05-26 11:01:14.378 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:01:14.378 FreshBooks[31878:698800] [DEBUG]: Adding auth to request [0x608000212a60]: https://freshbooks1495119909.zendesk.com/api/mobile/requests.json
2017-05-26 11:01:14.379 FreshBooks[31878:698800] [DEBUG]: About to execute [0x600000202df0]: https://freshbooks1495119909.zendesk.com/api/mobile/requests.json
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 3d456ebd7507b46cbef7e501c087f3824bd15472c9effe34e4444b0a94bed5b0";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "A7995028-9018-42E7-9FB5-E69D306C4C89";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:01:14.956 FreshBooks[31878:698800] [DEBUG]: Response code [0x600000202df0]: 201
2017-05-26 11:01:14.956 FreshBooks[31878:698800] [DEBUG]: Request success: [0x600000202df0]: https://freshbooks1495119909.zendesk.com/api/mobile/requests.json
2017-05-26 11:01:15.483 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:01:15.484 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:01:15.484 FreshBooks[31878:698800] [DEBUG]: SDK configuration file found in local storage
2017-05-26 11:01:15.485 FreshBooks[31878:698800] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2017-05-26 11:01:15.485 FreshBooks[31878:698800] [DEBUG]: Adding auth to request [0x600000200410]: https://freshbooks1495119909.zendesk.com/api/mobile/requests/show_many.json?tokens=nc6CZn3Ok4W7uqfGvAlTRAXZw&include=public_updated_at&status=new,open,pending,hold,solved&sort_by=updated_at&sort_order=desc
2017-05-26 11:01:15.486 FreshBooks[31878:698800] [DEBUG]: About to execute [0x600000206e80]: https://freshbooks1495119909.zendesk.com/api/mobile/requests/show_many.json?tokens=nc6CZn3Ok4W7uqfGvAlTRAXZw&include=public_updated_at&status=new,open,pending,hold,solved&sort_by=updated_at&sort_order=desc
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 3d456ebd7507b46cbef7e501c087f3824bd15472c9effe34e4444b0a94bed5b0";
    "Client-Identifier" = "mobile_sdk_client_d69242fd8a655b0e1253";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "A7995028-9018-42E7-9FB5-E69D306C4C89";
    "User-Agent" = "Zendesk-SDK/1.9.2.2 iOS/10.3 Env/Development";
}
2017-05-26 11:01:15.708 FreshBooks[31878:698800] [DEBUG]: Response code [0x600000206e80]: 200
2017-05-26 11:01:15.708 FreshBooks[31878:698800] [DEBUG]: Request success: [0x600000206e80]: https://freshbooks1495119909.zendesk.com/api/mobile/requests/show_many.json?tokens=nc6CZn3Ok4W7uqfGvAlTRAXZw&include=public_updated_at&status=new,open,pending,hold,solved&sort_by=updated_at&sort_order=desc
```

I can see that the `Mobile-Sdk-Identity` GUID has changed, but the tickets are still showing up under the same email address.

**Comment by tecknut** [comment] 2017-05-26 16:20
That could definitely be causing this.

Can you use a network sniffer like [Charles Proxy](https://www.charlesproxy.com/) to find out if that same bearer token is coming back each time `https://freshbooks1495119909.zendesk.com/access/sdk/anonymous` is called? 

This will help us find out if it's a client or server side error. 

Thanks

**Comment by blagh** [comment] 2017-05-29 14:25
It looks like the calls to login via `sdk/anonymous` are only happening in the first snippet...I can do the Charles Proxy stuff as requested, but I don't think I'll have any additional info :sweat_smile:

**Comment by tecknut** [comment] 2017-06-06 12:53
@blagh have you any updates on this?

**Comment by blagh** [comment] 2017-06-06 13:20
@tecknut I added a comment above...I can do the Charles Proxy sniffing, but I'll only have the results of the call to `sdk/anonymous` for the first identity, because the call to get a bearer token only happens for the first identity. So there won't be anything to compare.

**Comment by tecknut** [comment] 2017-06-06 14:59
@blagh I've tried replicating this, anytime I change the identity a new access call is made and a new token is fetched. 

Can you provide some snippets of the code your using in your app?

**Comment by blagh** [comment] 2017-06-06 20:52
@tecknut do you mean, other than the ones I've already provided in the description? I'll try making a small sample app, and see if I can reproduce.

**Comment by tecknut** [comment] 2017-06-06 21:12
If the code snippets you pasted above are copied directly from your integration that's fine. 

A sample app that reproduces this would be great if you can manage it. 

I've tested this across a few versions, so I don't think the version your using is the issue.

**Comment by blagh** [comment] 2017-06-06 22:47
@tecknut after making a sample app, it doesn't appear to reproduce the issue, so something else would appear to be going on. Just a shot in the dark, by chance does the behaviour depend on something in NSUserDefaults? We clear these when the user logs out.

**Comment by blagh** [comment] 2017-06-06 23:03
Clearing UserDefaults appears to be the culprit! I'll upload the whole thing to my github for posterity, but I just added this snippet to my sample app and that has reproduced the issue. 

    guard let applicationDomain = Bundle.main.bundleIdentifier else {
        return
    }

    UserDefaults.standard.removePersistentDomain(forName: applicationDomain)
    UserDefaults.standard.synchronize()

I'm not sure what would be the best course of action...although it's odd that the old identity would be retained _after_ clearing these defaults.

**Comment by blagh** [comment] 2017-06-06 23:09
@tecknut here is a minimal example of an app that reproduces the problem: https://github.com/blagh/zendesk-sdk-login-bug-repro/blob/master/ZendeskTest/ViewController.swift

We do have the capability to whitelist particular keys from being cleared...let me know what kinds of things would be most reasonable to try.

**Comment by tecknut** [comment] 2017-06-07 10:25
Thanks @blagh this helped track down the issue. 

We check user defaults when comparing a previously set identity. So when user defaults has been cleared the check assumes the user is new and we proceed to set it. The issue is there are still references to the previous user in memory. 

If you clear the user data before clearing user defaults, the data memory will also be cleared and things will work as desired. 

```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    // Clear all things user related.
    ZDKSdkStorage.instance().clearUserData()
    clearUserDefaults()
}
```

We've patched the issue internally and this will be out in our next release. The snippet above should get things working for you. 

Please verify this works for you. 

Thanks

**Comment by blagh** [comment] 2017-06-22 20:49
Hey sorry I just realized I forgot to respond to this! Adding the snippet works just fine, thanks for the help :smile:

**Comment by tecknut** [comment] 2017-06-26 09:05
Thanks ! gonna close this now

**Closed by tecknut** 2017-06-26 09:05 UTC
Labels: pending information
