### ISSUE TITLE
Regression in 1.5.4.1: Button for Ticket Attachments no longer shown on iPad

### ISSUE THREAD

**Issue by kuehnhammer** [zendesk/zendesk_sdk_ios#149] opened 2016-02-12 13:20 UTC
with the previous version, it was possible to attach files to new or existing tickets on the iphone and ipad. in the latest version, the relevant controls are missing from ZDKHelpCenter when running on an iPad.  compare attached screenshots... 

We use an existing nav controller:
[ZDKHelpCenter showHelpCenterWithNavController:self.targetNavigationController];

![screen shot 2016-02-12 at 14 17 07](https://cloud.githubusercontent.com/assets/1220339/13007895/67052932-d193-11e5-8719-c216ad57d72f.png)
![screen shot 2016-02-12 at 14 17 35](https://cloud.githubusercontent.com/assets/1220339/13007896/672c366c-d193-11e5-8382-8a7e973de38c.png)

**Comment by tecknut** [comment] 2016-02-12 13:47
@kuehnhammer Thanks for raising this. We're looking into this and we'll get back to you soon regarding a patch.

**Comment by tecknut** [comment] 2016-02-12 14:13
@kuehnhammer we can't replicate this. Can you give us a better idea of your setup please?

Is your iPad app landscape only?
Is this happening on iPad mini and full size iPad?
Is this happening on all versions of iOS supported by your app?

We've tried to replicate this on a few devices and on a few simulators. Any further info would be great. 

Thanks, 
Alan

**Comment by kuehnhammer** [comment] 2016-02-12 15:57
hi alan,

thanks for the quick reply!

yes, it's an older (pre-SizeClasses) universal app with a landscape-only iPad storyboard.
basically we have three view controller besides each other, and load your help center into the middle one.
we tested on full-size iPad and iPad Pro so far, both show the same problems.

i've derived a small integration project from the affected app that has the same behaviour:
[https://github.com/kuehnhammer/zendesk-integration-test](url)

might be related to device rotation... you'll definitely see the behaviour when holding the iPad in portrait and then launching the app, but i've also rebooted the device, launched the app while the iPad was in landscape, and still got the same behaviour.

the small camera button next to the comment field in existing tickets is also missing.

you can also use this to reproduce a second issue: when exiting the modal 'New Ticket' controller, the navigation controller's left boundary is reset to cover the leftmost view controller. 

screenshots of what you should be seeing are attached... 

thanks!
best, klaus
![screen shot 2016-02-12 at 16 42 53](https://cloud.githubusercontent.com/assets/1220339/13011907/4b5011be-d1a9-11e5-8ae9-8d2c197de9c0.png)
![screen shot 2016-02-12 at 16 43 05](https://cloud.githubusercontent.com/assets/1220339/13011909/4b79f01a-d1a9-11e5-8080-19d2ef2c4a51.png)
![screen shot 2016-02-12 at 16 43 21](https://cloud.githubusercontent.com/assets/1220339/13011908/4b749552-d1a9-11e5-843e-572207c7d3b8.png)

**Comment by tecknut** [comment] 2016-02-12 16:11
@kuehnhammer can you try something for us if it's not too much trouble? 

Can you verify that the attachment button is still in place when you revert to the previous version of the SDK?

**Comment by kuehnhammer** [comment] 2016-02-12 16:22
@tecknut just tried it with 1.5.3.1, and it's not working either.. no regression after all.
sorry about that, so it wasn't the version jump but just me jumping to conclusions.

i've definitely seen the buttons on the iPad though, and we have an (otherwise unrelated) issue report from our testers that implies the attachment button was visible on their iPad.

during setting up the test app i've also seen it working though, maybe it depends on just what rotation state the ipad is in. i've noticed in developing another app the the deviceRotation on the status bar can actually differ from what the rest of the views think, so who knows.

**Comment by tecknut** [comment] 2016-02-12 16:29
@kuehnhammer Can you check that attachments are enabled on your Zendesk instance? Since this issue persists through the different versions, the likely cause is that attachments have been disabled.
This can happen by someone manually changing the setting, or by an account plan downgrade. Going from a trial account to an essential account for instance. 

If you want to discuss any account specific details you may be better off opening a ticket with us at support.zendesk.com 

Alan

**Comment by kuehnhammer** [comment] 2016-02-12 16:33
@tecknut it can't be that, because the same code connecting to the same instance always works on the iPhone

**Comment by kuehnhammer** [comment] 2016-02-12 16:33
i checked the attachment setting, it's definitely enabled.

**Comment by tecknut** [comment] 2016-02-24 11:36
@kuehnhammer We've been trying to reproduce this and are still unable to. Can we see the code snippets for your integration please?

**Comment by StevenDiviney** [comment] 2016-04-05 14:28
@kuehnhammer Sorry for the delay on this. The behaviour you are seeing is intentional. We use UIImagePickerController for attachments. It does not support landscape and will crash if used in an app that does not support portrait.

We do our best to determine if an app supports portrait and show / hide the attachment buttons if it does but there is no easy way to do this at runtime. We have attempted to tighten it up to prevent more crashes so that might be why you noticed a change.

Given the choice between no attachments and a hard crash we chose the former. A full fix is to create our own image picker but I can't say when that will happen.

**Comment by RonanMcH** [comment] 2016-07-05 15:48
Hi @kuehnhammer ,
As Steven stated, this is all intentional for an application that doesn't support portrait. I am going to close this issue. Please feel free to open another for any other issues you may encounter with the Support SDK.
Thanks,
Ronan.

**Closed by RonanMcH** 2016-07-05 15:48 UTC
Labels: bug
