### ISSUE TITLE
ZDKRMA RateMyApp dialog silently fails in non-portrait orientations on iPhone

### ISSUE THREAD

**Issue by INRIX-Patrick-Winchell** [zendesk/zendesk_sdk_ios#180] opened 2016-05-19 18:20 UTC
Xcode 7.3.1
iOS 9.3
All iPhone sizes - Issue is not present on iPad.
SDK: 1.6.1.1

REPRO STEPS:
1. Rotate to landscape or upside-down orientation on an iPhone
2. Activate ZDKRMA by showAlwaysInView: .

EXPECTED RESULT:
Dialog appears

ACTUAL RESULT:
Nothing happens. There is also no log or obvious completionBlock/delegate method for checking if the dialog was shown. Same result happens for showInView: .

Additionally rotation while a dialog is being displayed will change the status bar position, but will not change the orientation of the dialog or the background view.

**Comment by RonanMcH** [comment] 2016-05-20 08:33
Hi @INRIX-Patrick-Winchell ,
I have managed to reproduce this issue and I have documented an internal bug for it so that we can track it. We will keep this issue open till it has been fixed and we released with the fix. Unfortunately, I cannot give a timeline for this. 
Thanks for bringing this to our attention,
Ronan.

**Comment by RonanMcH** [comment] 2016-05-23 09:19
Hi @INRIX-Patrick-Winchell ,
I have looked into the first issue of the dialog box not appearing in landscape. After discussing with my colleagues, this is not a bug but the intended behaviour. Although the second issue, when the user rotates to landscape and the RMA dialog box doesn't rotate is an edge case that we need to look into.  I shall keep the issue open for this.
Thanks again,
Ronan.

**Comment by RonanMcH** [comment] 2017-07-04 14:54
Hi @INRIX-Patrick-Winchell ,
We deprecated the RMA feature in the SDK and it will be removed in the next release. We have built an open source alternative, available [here](https://github.com/zendesk/rate_my_app_ios) that works in conjunction with the SDK. 
Thanks,
Ronan.

**Closed by RonanMcH** 2017-07-04 14:54 UTC
Labels: bug
