### ISSUE TITLE
receiving Cocoapods error

### ISSUE THREAD

**Issue by Prince2k3** [zendesk/zendesk_sdk_ios#37] opened 2015-07-07 19:21 UTC
when trying to install Zendesk with Cocopods I get this error ... (Note: Project is done in Swift)

[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/.../Documents/Xcode/../iOS/Pods/ZendeskSDK/ZendeskSDK.framework)

**Comment by Prince2k3** [comment] 2015-07-07 20:34
Zendesk Mobile SDK 1.3.0.1 is completely broken. I went back to the version before this and everything works just fine. That or you need to update your documentation to get folks working with 1.3.0.1

**Comment by tecknut** [comment] 2015-07-09 13:33
Hey @Prince2k3, 

Can you put a snippet of your Podfile in this issue please? We have tested locally and have no issue with installing the current version of the SDK through cocoapods. 

Thanks

**Comment by Prince2k3** [comment] 2015-07-09 15:44
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 1.2'
pod 'UICountingLabel'
pod 'Timepiece', :git => "https://github.com/naoty/Timepiece.git"
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
pod 'TTTAttributedLabel'
pod 'MBProgressHUD'

**Comment by Prince2k3** [comment] 2015-07-09 16:13
thats with zendesk removed...I ended up downloading it

**Comment by tecknut** [comment] 2015-07-09 18:38
Could you try adding `pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git'` to it again? It would be good to replicate the issues so we can fix what ever is causing it.

**Comment by Prince2k3** [comment] 2015-07-10 19:04
I get the message stated above when I add that line

**Comment by PorterHoskins** [comment] 2015-07-15 01:43
`use_frameworks!` is the issue. I can remove that line and it works fine. Problem is I can't remove that line because of my other pods.

I even tried downloading it and manually adding it to the project and I would get linker issues.

```Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ZDKMockNetworkProtocol", referenced from:
      _OBJC_CLASS_$_ZDKFailureProtocol in ZendeskSDK(ZDKFailureProtocol.o)
  "_OBJC_METACLASS_$_ZDKMockNetworkProtocol", referenced from:
      _OBJC_METACLASS_$_ZDKFailureProtocol in ZendeskSDK(ZDKFailureProtocol.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by tecknut** [comment] 2015-07-15 09:37
@PorterHoskins We have just released a patch for the symbol errors. 

@Prince2k3 We are currently working on adding another sub spec which will have a dynamic build of our SDK. The issue you're having is due to the static linked binary. `use_frameworks!` expects the binary type to be dynamically linked. We will be testing this today.

**Comment by mkoppanen** [comment] 2015-07-28 01:04
Any news on this?

**Comment by adrianmacneil** [comment] 2015-10-07 00:06
Is this still a problem? I'm getting a similar error with Swift and `use_frameworks!`:

    Undefined symbols for architecture x86_64:
      "_kUTTypeImage", referenced from:
          -[ZDKCreateRequestViewController imagePickerController:didFinishPickingMediaWithInfo:] in ZendeskSDK(ZDKCreateRequestViewController.o)
    ld: symbol(s) not found for architecture x86_64

**Comment by adrianmacneil** [comment] 2015-10-07 00:55
Nevermind. I solved the above error by manually linking `MobileCoreServices.framework`. For anyone else with same issue:

1. Select your project in your navigator
2. Visit "General" tab
3. Under "Linked Frameworks and Libraries", click +
4. Add `MobileCoreServices.framework`

**Comment by baz8080** [comment] 2015-10-07 14:40
@adrianmacneil This isn't something that we can replicate every time. We're going to see if linking `MobileCoreServices.framework` in our podspec fixes it though.

**Comment by tecknut** [comment] 2015-10-16 12:20
@adrianmacneil We've just added some framework dependancies to our podspec. It should fix the issue for any new integrators. Thanks for raising this with us.

**Comment by tecknut** [comment] 2015-10-19 10:22
@Prince2k3 We've tested this a few times recently with a swift project and can't reproduce the error. We're going to close this. If you experience this error again please reopen the issue.

Thanks.

**Closed by tecknut** 2015-10-19 10:22 UTC

**Comment by wrfellows** [comment] 2016-01-15 22:24
<img width="1001" alt="screen shot 2016-01-16 at 3 24 04 am" src="https://cloud.githubusercontent.com/assets/13545330/12366987/aa3c54f8-bc00-11e5-821c-b6acb31c7395.png">

This is issue is happening again!
