### ISSUE TITLE
iOS app attempt to access privacy-sensitive data without a usage description

### ISSUE THREAD

**Issue by frantisan** [zendesk/zendesk_sdk_ios#261] opened 2016-12-12 14:04 UTC
Hi
We got the following error message in iTunes Connect right after uploading the binary of our application.

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "XYZ". To process your delivery, the following issues must be corrected:
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

Our app uses two resources (camera and photo album) for which we need to put two keys in the "info.plist" file. These keys are:

- NSCalendarsUsageDescription

- NSPhotoLibraryUsageDescription

The app works OK, it doesn't crash on iOS 10. However, when uploading the file to iTunes Connect they said that those 2 mentioned keys still need to be included.

Looking the Zendesk SDK, we've noticed that there are two places in which you've put your own "info.plist" file, so we think Apple is reading those two extra files and hence the error.

We've added the two mentioned key to your SDK "info.plist" files and we've redelivered the build to iTunes again, getting the same result.

We removed the Zendesk SDK from our app to be able to redeliver it to iTunes Connect and they've approved it.

If you find out a way to solve this problem with the latest iOS Zendesk SDK, please let us know so that we can include it again.

- SDK version: 1.7.6.1
- Xcode version: Version 8.1 (8B62)
- iOS or Simulator: iOS 10.1.1 , iOS 9.3.2 compiled with Xcode 8.1
- iOS Version: iOS 9, iOS 10
- Swift version: 2.3

Steps to Reproduce:

1. Install via Cocoapods Zendesk SDK for iOS 
2. Add NSCalendarsUsageDescription and NSPhotoLibraryUsageDescription to project.
3. Send binary to iTunes Connect
4. Read iTunes Connect email with error

**Comment by mathewcropper** [comment] 2016-12-12 14:18
Hi. This is covered in our sixteenth here: https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk#update-usage-descriptions-in-info.plist

The Support SDK uses NSPhotoLibraryUsageDescription and NSCameraUsageDescription, and so an entry in your info.plist is required. We don't plan to change this in future, as both are needed to allow us to attach images to requests.

**Comment by oarrabi** [comment] 2016-12-12 15:26
Hello @frantisan,

As an update to what @mathewcropper said.
I noticed that you only adding `NSPhotoLibraryUsageDescription ` to your application, you might need to add `NSCameraUsageDescription`.

We will try to reproduce the issue and replicate adding only `NSPhotoLibraryUsageDescription` to the project.

Can you please add `NSCameraUsageDescription` and try again?

Thanks

**Comment by jdsk8r** [comment] 2016-12-13 13:23
Hi @oarrabi, I work in the same project as @frantisan, we will try this once again, but we are skeptical this might work. As we wrote it above we have included both keys NSPhotoLibraryUsageDescription and NSCameraUsageDescription in all the 3 info.plist files (to the one on the main project plus on the 2 that are part of zendesk sdk http://tinyurl.com/jfq92fh http://tinyurl.com/zo3yqcj ) as it is stated on your documentation.
Have you guys heard of anyone else having these issues? (with apps compiled with xcode 8.1 being rejected by apple due to this issue)

**Comment by frantisan** [comment] 2016-12-13 16:33
Hi @mathewcropper @oarrabi 

We made it work by setting a default value on the keys

- NSCalendarsUsageDescription = "something"

- NSPhotoLibraryUsageDescription = "something"

In our case, we have several applications that support 2 languages, english and norwegian, and what I usually do is to implement a _InfoPlist.strings_ file in which I put the strings previously mentioned with their corresponding values for each language.

What we did before is to add those keys without a predefined value, something like:

- NSCalendarsUsageDescription = ""
- NSPhotoLibraryUsageDescription = ""

By doing it like this way we had never had any problems until now that we have implemented the Zendesk SDK.
It looks like Apple is validating (if it exists more than one _info.plist_ file in the project) that the key(s) contain(s) some value by default to be able to pass their validation.

Without further ado, I think you can close this issue.

Thanks.

**Comment by StevenDiviney** [comment] 2016-12-13 17:14
@frantisan @jdsk8r Are you adding NSCameraUsageDescription or NSCalendarsUsageDescription? You don't mention NSCameraUsageDescription in your issue.

**Comment by frantisan** [comment] 2016-12-13 17:41
@StevenDiviney 

Excuse, was my mistake.
- NSPhotoLibraryUsageDescription
- NSCameraUsageDescription

**Comment by tecknut** [comment] 2016-12-14 11:07
It seems like this has been solved. We're gonna close this again for now.

**Closed by tecknut** 2016-12-14 11:07 UTC
