### ISSUE TITLE
Crash on navigation to Zendesk UI

### ISSUE THREAD

**Issue by zeulb** [zendesk/zendesk_sdk_ios#479] opened 2019-01-17 22:55 UTC
- SDK version: tried both 2.2.0 and 2.3.0 
- Xcode version: 10.1
- iOS or Simulator: Simulator
- iOS Version: 12.1
- Installation: Tried both manual ObjC and CocoaPod

Trying to integrate Zendesk SDK to a React Native Expo app.
Did init and identify successfully but crash when navigating to any UI from Zendesk

```
  UIViewController *tickets = [ZDKRequestUi buildRequestList];
  [rootViewController presentViewController:tickets animated:YES completion:^{}];
```

This is even reproducable on a clean expo app installation.

Below is the stacktrace of the crash.

```
2019-01-17 14:48:55.983866-0800 testing[58842:858811] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fa921bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e1aa735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f9de4ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010f9ba775 -[__NSArrayM insertObject:atIndex:] + 1269
	4   ZendeskProviderSDK                  0x000000010ceec061 __42+[ZDKLocalization buildInitialBundleArray]_block_invoke + 234
	5   CoreFoundation                      0x000000010f9bab9c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	6   ZendeskProviderSDK                  0x000000010ceebf47 +[ZDKLocalization buildInitialBundleArray] + 201
	7   ZendeskProviderSDK                  0x000000010ceec5a1 __31+[ZDKLocalization setupBundles]_block_invoke + 105
	8   libdispatch.dylib                   0x0000000110af8602 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x0000000110afa0c4 _dispatch_once_callout + 66
	10  ZendeskProviderSDK                  0x000000010ceec536 +[ZDKLocalization setupBundles] + 86
	11  ZendeskProviderSDK                  0x000000010ceebb5b +[ZDKLocalization localizedStringWithKey:] + 52
	12  ZendeskSDK                          0x000000010d0fe986 globalinit_33_3809F06811590C3BFF7A94607690EF24_func99 + 102
	13  libdispatch.dylib                   0x0000000110af8602 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x0000000110afa0c4 _dispatch_once_callout + 66
	15  libswiftCore.dylib                  0x00000001292a2ea9 swift_once + 25
	16  ZendeskSDK                          0x000000010d0fe9f4 $S10ZendeskSDK9ConstantsO7StringsO16requestListTitleSSvau + 36
	17  ZendeskSDK                          0x000000010d139732 $S10ZendeskSDK25RequestListViewControllerC11viewDidLoadyyF + 786
	18  ZendeskSDK                          0x000000010d13bc24 $S10ZendeskSDK25RequestListViewControllerC11viewDidLoadyyFTo + 36
	19  UIKitCore                           0x000000011878c4e1 -[UIViewController loadViewIfRequired] + 1186
	20  UIKitCore                           0x000000011878c940 -[UIViewController view] + 27
	21  UIKitCore                           0x00000001186af4ee -[_UIFullscreenPresentationController _setPresentedViewController:] + 89
	22  UIKitCore                           0x00000001186a2edf -[UIPresentationController initWithPresentedViewController:presentingViewController:] + 133
	23  UIKitCore                           0x000000011879f9ad -[UIViewController _presentViewController:withAnimationController:completion:] + 3713
	24  UIKitCore                           0x00000001187a274b __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 99
	25  UIKitCore                           0x00000001187a2dd9 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	26  UIKitCore                           0x00000001187a26b1 -[UIViewController _presentViewController:animated:completion:] + 173
	27  UIKitCore                           0x00000001187a29f0 -[UIViewController presentViewController:animated:completion:] + 150
	28  testing                             0x000000010505eacd -[EXViewController presentViewController:animated:completion:] + 461
	29  testing                             0x000000010554ad0f -[RNZendesk showHelpCenter] + 207
	30  CoreFoundation                      0x000000010fa9903c __invoking___ + 140
	31  CoreFoundation                      0x000000010fa964d5 -[NSInvocation invoke] + 325
	32  CoreFoundation                      0x000000010fa96926 -[NSInvocation invokeWithTarget:] + 54
	33  testing                             0x00000001053f5b4a -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810
	34  testing                             0x00000001054035d6 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790
	35  testing                             0x00000001054030ef _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
	36  testing                             0x0000000105403069 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	37  libdispatch.dylib                   0x0000000110af7595 _dispatch_call_block_and_release + 12
	38  libdispatch.dylib                   0x0000000110af8602 _dispatch_client_callout + 8
	39  libdispatch.dylib                   0x0000000110b0599a _dispatch_main_queue_callback_4CF + 1541
	40  CoreFoundation                      0x000000010f9f73e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	41  CoreFoundation                      0x000000010f9f1a76 __CFRunLoopRun + 2342
	42  CoreFoundation                      0x000000010f9f0e11 CFRunLoopRunSpecific + 625
	43  GraphicsServices                    0x0000000111ee01dd GSEventRunModal + 62
	44  UIKitCore                           0x0000000118dab81d UIApplicationMain + 140
	45  testing                             0x0000000104bd4250 main + 112
	46  libdyld.dylib                       0x0000000110b6e575 start + 1
	47  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Also notice that `[ZDKLocalization printAllKeys];` doesn't print out anything, but pretty sure `Strings.bundle` is already copied as resource.

**Comment by schlan** [comment] 2019-01-30 16:43
This is a duplicate of https://github.com/zendesk/zendesk_sdk_ios/issues/477. Please follow this issue for further updates.

**Closed by schlan** 2019-01-30 16:43 UTC
