### ISSUE TITLE
ZDKUITextViewDelegate.h uses private APIs in iOS 10

### ISSUE THREAD

**Issue by platedbay** [zendesk/zendesk_sdk_ios#222] opened 2016-09-10 20:33 UTC
Hello,

We've submitted our application with iOS 10 compatibility for review. We just got rejected because it seems our application is now using some private APIs. One of which came back as:

`updateLayout:`

I've verified that our codebase does not call this method, and running a `grep -r updateLayout .` in my workspace's directly indicates that the ZendeskSDK is:

> Bay$ grep -r updateLayout .
./Pods/ZendeskSDK/ZendeskSDK.framework/Headers/ZDKUITextViewDelegate.h:- (void) updateLayout:(ZDKUITextView*)textView;
Binary file ./Pods/ZendeskSDK/ZendeskSDK.framework/ZendeskSDK matches

It's my best guess that this is causing an issue for us. Am I mistaken? We have the most up to date version via Cocoapods.

Thanks!

**Comment by lightbow** [comment] 2016-09-11 17:09
Yikes. Any experimentation to see if rolling back to an older version gets around this, or does this issue basically block all iOS app submissions containing Zendesk SDK?

**Comment by mathewcropper** [comment] 2016-09-12 05:55
Hi there. Thanks for raising this.

The SDK doesn't use any private APIs, but for some time it has had a method with the same name as one. My guess is that there's an automation in place that is flagging it as a false positive.

We will update the SDK to use a new name. We'll post here when it is released to update you. My hope is that we'll have this out today, and at the very latest tomorrow.

**Comment by platedbay** [comment] 2016-09-12 11:37
Awesome! Thank you so much @mathewcropper

**Comment by mathewcropper** [comment] 2016-09-12 13:43
Hi there. We just released v1.7.2.1, which contains this fix. I'll mark this issue as closed, but if you have any further issues just let me know.

**Comment by platedbay** [comment] 2016-09-12 13:56
Talk about a turn time! Thank you so much 💯

**Comment by mathewcropper** [comment] 2016-09-12 14:03
I can't take credit.. @tecknut and @RonanMcH did all the hard work. Props to them 😄

**Comment by platedbay** [comment] 2016-09-12 14:18
Well thank you @tecknut and @RonanMcH . I owe you both a 🍺

**Comment by sxua** [comment] 2016-09-13 18:05
Hi guys, I'm afraid, it's not the end of the story yet, because we've got a rejection too because of "layoutSubview" method in `ZDKUITextView` class.

**Comment by mathewcropper** [comment] 2016-09-13 19:29
Hi @sxua. Thanks for flagging this. We thought we'd caught everything, but clearly not. 

We will work on this and put out another release as soon as we can. 

If your app update is urgent, I would recommend disputing the decision. It's not a use of the private API, but a clashing method name. If you can wait, we will hopefully have an update out in the next day or two.

**Comment by sxua** [comment] 2016-09-13 19:31
@mathewcropper Thanks, we actually already appealed and review team said that the problem is in calling `updateLayout:` method from `[ZDKUITextView layoutSubviews]`.

**Comment by mathewcropper** [comment] 2016-09-13 19:37
To be on the safe side I want to re-run a full check for disallowed names. I'd hang on until the release if you already appealed and they stuck to their guns. 

I'm terribly sorry about this. We'll keep you posted.

**Comment by mathewcropper** [comment] 2016-09-14 09:10
Hi @sxua! Have you updated to use version 1.7.2.1? In the latest version of the Support SDK with the fix for this, we aren't seeing any left over references to it.

I'll leave this open for you to respond, but I suspect you're on v1.7.1.1 or earlier. Upgrading will fix this issue for you.

**Comment by sxua** [comment] 2016-09-14 13:06
Hi @mathewcropper,

Thanks for the update on this. I've checked binary of 1.7.2.1 and found out that there's no `updateLayout:` method anymore, instead there is an `updateTextViewLayout:`.
And yeah, we were using version 1.6.x, sorry for confusion. This issue can be closed.

**Closed** 2016-09-19 08:27 UTC
Labels: bug
