### ISSUE TITLE
HelpCenterProvider fails with error ZDDispatcher code = 3, zd_dispatcher_err=HTTP Error: 422

### ISSUE THREAD

**Issue by dmitryrybakov** [zendesk/zendesk_sdk_ios#156] opened 2016-02-26 20:28 UTC
I have successfully initialized ZenDesk SDK for iOS by calling method initializeWithAppId with appropriate appId, clientId and JWT identity. Unfortunately I have faced with an error calling the function ZDKHelpCenterProvider::getFlatArticlesWithCallback. The error description says the following:
Error Domain=ZDDispatcher Code=3 "(null)" UserInfo={zd_dispatcher_err=HTTP Error: 422}
I am wondering if there some error description and why this error happened. Could you please help me providing some kind of information?

**Comment by baz8080** [comment] 2016-02-27 11:39
Hi @dmitryrybakov 

Happy to help you here, but debugging JWT issues usually requires us to ask you for test tokens and details of your account, so creating a ticket with us at support@zendesk.com might be better.

Have you tried to call your JWT endpoint with the same token that you're using in the ZDKJwtIdentity?

```
curl -v -X POST "https://yourjwtendpoint.example.com" -d "user_token=your_user_token"
```

In the response we'll need name and email, as per the [docs](https://developer.zendesk.com/embeddables/docs/ios/authentication#jwt-authentication).

**Comment by dmitryrybakov** [comment] 2016-02-27 17:31
Hello Barry,
   Thank you for the quick reply. The curl request work fine with the JWT endpoint  https://api-v21.breezy.com/sso/zendesk . It seems that I have mistyped the JWT endpoint in admin console. I want just to clarify information about the settings and what goes where:
*  In admin console JWT token and JWT endpoint -  https://api-v21.breezy.com/sso/zendesk  
*  In the code base  -  BR_ZENDESK_URL =  @"https://breezy.zendesk.com" ; AppId and ClientId    With the above settings I am getting the next error:
"The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1012.)", NSErrorFailingURLKey=https://breezy.zendesk.com/access/sdk/jwt     The last part of the failing URL looks strange. How to tell an API to use the path "/ssso/zendesk" instead of "/access/sdk/jwt" ?

Best regards,
Dmitry

**Comment by baz8080** [comment] 2016-02-27 18:22
Hey Dmitry,

I'm seeing two issues which might be preventing you from getting a token. Btw - the SDK doesn't directly call your JWT endpoint, our `/access/sdk/jwt ` will do that.

1) Users must be end-users

I saw some logs where an email address belonging to an agent was used. This will fail because we only allow identification of end users

2) Signatures

We had some issues verifying your payload's signature. Please check that you're using the full secret that you got from the agent interface when setting up your app. For security reasons we only show the first 9 characters after the first time it is shown. If you've forgotten it, you can regenerate a new secret in the admin interface though. Just navigate to your app, scroll to the bottom and click 'generate new secret' (and update your JWT service to use it ;) ).

I hope that 1 or 2 sorts it out. If not we'll be able to debug more on Monday.

Thanks!
Barry.

**Comment by dmitryrybakov** [comment] 2016-02-27 18:39
Hi Barry,
  2. Got it
  1. Sorry, I probably did not understand the first time, but what the difference between agent and end-user? As I understand our test development account  dev@breezy.com  is like emulation of end-user. Again I do not understand what is agent. In any case thank you for the information and we can elaborate on this on Monday.

Best regards,
Dmitry

**Comment by baz8080** [comment] 2016-02-27 18:48
Hi Dmitry,

There's [a lot of info](https://support.zendesk.com/hc/en-us/articles/203661776-Understanding-Zendesk-user-roles) on the differences, but in this case an end-user in Zendesk will be a user created by our SDK, which maps to one of your customers. An agent will be someone in your company who is giving them support.

Thanks,
Barry.

**Comment by baz8080** [comment] 2016-02-27 18:50
Sorry, forgot to add. If your JWT payload sends back an email address associated with an agent then we will block authentication. Perhaps dev@breezy.com is associated with an admin user.

**Comment by dmitryrybakov** [comment] 2016-02-27 19:11
It seems that there is no an email in the payload:
{"jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0NTY1OTE2MjksImp0aSI6ImE2NWZkMDhhLTY2MTUtNDQyYy1hMWM3LTE0N2ZmYmJlMjYxMyIsIm5hbWUiOiJEZXYgQnJlZXp5IiwiZW1haWwiOiJkZXZAYnJlZXp5LmNvbSJ9.iRIhiCZUUW4QHUHw34rXVMouKqE1zEJcJ2Zp_jjq6Kw"} I will try another email which is associated with the different user.

**Comment by baz8080** [comment] 2016-02-28 10:05
Hey Dmitry,

[Jwt.io](https://jwt.io) is pretty cool for testing JWT stuff. The decoded payload from the JWT you posted is:

```javascript
{
  "iat": <redacted>,
  "jti": "<redacted>",
  "name": "Dev Breezy",
  "email": "dev@breezy.com"
}
```

**Comment by dmitryrybakov** [comment] 2016-02-28 15:10
Hi Barry,
   I have tried a different email  stas.razbiegin@srost-studio.com . The error is the same: NSErrorFailingURLKey=https://breezy.zendesk.com/access/sdk/jwt

I have tried to verify JWT using Jwt.io, I have got next info:
{
"iat": code,
"jti": "code",
"name": "stas.razbiegin@srost-studio.com",
"email": "stas.razbiegin@srost-studio.com"
} It seems to be correct but SDK does not work with this identity. I might duplicate the question, but are there some settings that control the prefix: access/sdk/jwt ?


>Воскресенье, 28 февраля 2016, 2:05 -08:00 от Barry Carroll <notifications@github.com>:
>
>Hey Dmitry,
>Jwt.io is pretty cool for testing JWT stuff. The decoded payload from the JWT you posted is:
>{
  "iat": <redacted>,
  "jti": "<redacted>",
  "name": "Dev Breezy",
  "email": "dev@breezy.com"
}

**Comment by dmitryrybakov** [comment] 2016-02-29 16:44
Hello Barry,
    Just to be informed. I have created the ticket:  https://support.zendesk.com/hc/requests/1488110

Best regards,
Dmitry

>Воскресенье, 28 февраля 2016, 12:05 +02:00 от Barry Carroll <notifications@github.com>:
>
>Hey Dmitry,
>Jwt.io is pretty cool for testing JWT stuff. The decoded payload from the JWT you posted is:
>{
  "iat": <redacted>,
  "jti": "<redacted>",
  "name": "Dev Breezy",
  "email": "dev@breezy.com"
}

**Comment by oarrabi** [comment] 2016-03-01 13:19
Hello @dmitryrybakov,

I will close this issue as it was confirmed to be fixed on the support ticket https://support.zendesk.com/hc/requests/1488110.

If you face any other issue, please don't hesitate to open a new issue on GitHub or submit a ticket.

**Closed by oarrabi** 2016-03-01 13:19 UTC
Labels: help wanted, pending information
