### ISSUE TITLE
Frame goes wrong when choosing to send a feedback from RMA

### ISSUE THREAD

**Issue by xareelee** [zendesk/zendesk_sdk_ios#32] opened 2015-05-24 18:00 UTC
After choosing to send a feedback from RMA, the alert view shows wrong frame (on iOS 8.3/Zendesk 1.2.0.1, occurred in both iOS Simulator and iPhone 6+). BTW, I use `-showAlwaysInView:` to show the RMA.

![ios simulator screen shot may 25 2015 01 48 33](https://cloud.githubusercontent.com/assets/804308/7788929/ec83de10-0280-11e5-8b79-1cb6ab998b76.png)

It obviously moved up as shown in Reveal.app:

![screen shot 2015-05-25 at 01 49 21](https://cloud.githubusercontent.com/assets/804308/7788933/05ad0786-0281-11e5-8e04-e2675583dcd6.png)

It still shows correct RMA alert view when the keyboard was not shown.

![ios simulator screen shot may 25 2015 01 49 45](https://cloud.githubusercontent.com/assets/804308/7788946/b4acad9a-0281-11e5-9f95-879d3c562c8c.png)
![screen shot 2015-05-25 at 01 49 53](https://cloud.githubusercontent.com/assets/804308/7788947/b732a010-0281-11e5-869b-45e5db66b122.png)

**Comment by xareelee** [comment] 2015-05-25 04:48
I found the problem occurs when installing [**IQKeyboardManager**](https://github.com/hackiftekhar/IQKeyboardManager) together with ZendeskSDK. It moves the view incorrectly when detecting the keyboard event for text fields.

**Comment by xareelee** [comment] 2015-05-25 05:04
I've tried to add `[[IQKeyboardManager sharedManager] disableInViewControllerClass:[ZDKRMADialogViewController class]];` to disable the IQKeyboardManager in ZDKRMADialogViewController, but it still doesn't work.

Because ZDKRMADialogViewController is non-public, please help fix this issue (by either IQKeyboardManager or ZDKRMADialogViewController). Thanks!

**Comment by xareelee** [comment] 2015-06-01 03:26
I found that the problem is not just about IQKeyboardManager. I want to control showing RMA view by calling -showAlwaysInView:, but it will be shown normally on iOS Simulator except on iDevices.

**Comment by BPlano** [comment] 2015-06-08 12:37
@xareelee, this should be fixed as of our SDK 1.3.0.1 release. Could you download that and check to see if the issue is resolved?

**Comment by xareelee** [comment] 2015-06-09 18:10
@BPlano, thanks for your reply. I'm glad to try SDK 1.3.0.1, but please accept the pull request #33 first.

I current use cocoapods to install a forked ZendeskSDK with the modified `.podspec`.

```ruby
pod 'ZendeskSDK/Core', :git => 'https://github.com/PRIVATE_FORKED/zendesk_sdk_ios.git'
```

**Comment by BPlano** [comment] 2015-06-09 18:25
Hey @xareelee, thanks for pointing that out. Will get that looked at sometime soon :)

**Comment by xareelee** [comment] 2015-06-24 10:35
@BPlano, It's better now, but still has a little layout problem. I use the following images to illustrate the current issue in the version 1.3.0.1:

##### (1) **feedback view** layout without IQKeyboardManager

It shows the full frame of the feedback view now, but it is not vertically centered in the visible area.

![ios simulator screen shot jun 24 2015 18 01 44](https://cloud.githubusercontent.com/assets/804308/8327726/25cf7d1c-1a9d-11e5-9a22-df9772e08d69.png)


##### (2) **feedback view** layout with IQKeyboardManager

After including **IQKeyboardManager**, the frame of the feedback view will mask the status bar.

![ios simulator screen shot jun 24 2015 18 07 10](https://cloud.githubusercontent.com/assets/804308/8327941/da82e1bc-1a9e-11e5-926e-a03e06b65b84.png)

Hope you can help fix this problem. :)

**Comment by hackiftekhar** [comment] 2015-06-28 03:15
@xareelee You should try disabling IQKeboardManager and keyboard toolbar in order to fix above issue.

**Comment by tecknut** [comment] 2015-09-15 13:50
@xareelee is this still an issue for you?

**Comment by xareelee** [comment] 2015-09-22 07:49
I've already fixed this issue by myself using KVO (key-value observation via ReactiveCocoa) to correct the frame. I did not test it without the frame correction.

**Closed** 2015-09-22 08:03 UTC
