### ISSUE TITLE
Black area over keyboard if user is trying to add comment

### ISSUE THREAD

**Issue by Pitsko** [zendesk/zendesk_sdk_ios#114] opened 2015-11-11 08:46 UTC
please see image
<img width="323" alt="screenshot 2015-11-11 00 44 37" src="https://cloud.githubusercontent.com/assets/172434/11087240/91d2d1a2-880d-11e5-9e13-498bf1e85afc.png">

**Comment by RonanMcH** [comment] 2015-11-11 10:39
Hi Pitsko,
I am struggling to recreate this bug, although we have seen it before on a different OS version and device. What method are you using to open your request list? 
Thanks,
Ronan.

**Comment by RonanMcH** [comment] 2015-11-11 16:09
Hi again @Pitsko,
after talking to one of my colleagues, he explained that this is an issue he has seen before and has a minor workaround to fix it. 
You would need to add the following methods to the viewController that calls the [ZDKRequests showRequestCreationWithNavController:(UINavigationController*)navController;]:

```
- (void)lowerBottomLayoutGuide {

    if ([[ZDKUIViewController topViewController] isKindOfClass:[ZDKUIViewController class]]) {
        [self setLayoutGuide:ZDKLayoutRespectTop onController:(ZDKUIViewController*)[ZDKUIViewController topViewController]];
    }
}

- (void)raiseBottomLayoutGuid {
    if ([[ZDKUIViewController topViewController] isKindOfClass:[ZDKUIViewController class]]) {
        [self setLayoutGuide:ZDKLayoutRespectAll onController:(ZDKUIViewController*)[ZDKUIViewController topViewController]];
    }
}

- (void)setLayoutGuide:(ZDKLayoutGuide)guide onController:(ZDKUIViewController*)controller {
    controller.layoutGuide = guide;
}
```

and then register for keyboard notifications:
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(lowerBottomLayoutGuide) name:UIKeyboardWillShowNotification object:nil];
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(raiseBottomLayoutGuid) name:UIKeyboardWillHideNotification object:nil];
```
Hope this fix works for you,
Ronan.

**Comment by Pitsko** [comment] 2015-11-12 18:59
Hi, thank you for help
But this issue not related to creation ticket
User open list of tickets -> tap on one of them -> tap comment input. 
So I can't override anything here, because it is related to your internal controllers, from your library

**Comment by tecknut** [comment] 2015-11-12 19:06
@Pitsko the methods which lower and raise the layout guide get the SDK controller which is currently visible. 

```
...
....onController:(ZDKUIViewController*)[ZDKUIViewController topViewController]];
...
```

Putting these methods in the controller where you present the SDK will work. 

Just be sure to call remove observer in the dealoc of the view controller you put this code in.

```
- (void)dealoc {
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
```

**Comment by RonanMcH** [comment] 2015-11-23 13:48
Hi @Pitsko ,
I hope this fix worked for you.  I am going to tentatively close this issue but feel free to reopen it if the issue has not been solved for you.
Ronan.

**Comment by jaernouts** [comment] 2016-02-05 07:07
Hello @RonanMcH, @tecknut, I want to reopen this issue because I have that same issue on my Help Center, when a user taps the search bar... I added the workaround code, but this doesn't change anything. I use a helper to handel everything regarding Zendesk and this helper uses following code:
`    [ZDKConfig instance].userLocale = [[NSBundle mainBundle].preferredLocalizations firstObject];
    
    [[ZDKSupportView appearance] setNoResultsFoundLabelFont:[UIFont fontWithName:FontNameRegular size:14.0f]];
    [[ZDKSupportArticleTableViewCell appearance] setArticleParentsLabelFont:[UIFont fontWithName:FontNameRegular size:14.0f]];
    [[ZDKSupportArticleTableViewCell appearance] setTitleLabelFont:[UIFont fontWithName:FontNameRegular size:16.0f]];
    [[ZDKSupportTableViewCell appearance] setTitleLabelFont:[UIFont fontWithName:FontNameRegular size:14.0f]];
    
    [ZDKHelpCenter setNavBarConversationsUIType:ZDKNavBarConversationsUITypeNone];
    [[UINavigationBar appearance] setTranslucent:NO];
    [ZDKHelpCenter showHelpCenterWithNavController:navigationController];`

I tried to add your fix as well in the helper as in the ViewController which calls the helper method, but both don't work. Can you please take a look again?

Oh, I'm on version 1.5.3.1, just so you know!

Thx!

**Comment by schlan** [comment] 2016-02-17 13:56
Hi @jaernouts, sorry for the late reply. For further debugging, can you share the helper you're using? Feel free to open a ticket with us, if you don't want to share it publicly.

**Comment by baz8080** [comment] 2016-02-23 14:33
Hi @jaernouts , do you still need some help on this issue?

**Comment by jaernouts** [comment] 2016-02-25 06:00
Sorry, I missed the previous comment.

The helper I'm using is a class with a 'setup' function and exactly the function I already provided earlier:
```
- (void)initializeZendesk {
    NSString *zendeskAppId    = [LocalizationManager zendeskAppId];
    NSString *zendeskURL      = [LocalizationManager zendeskUrl];
    NSString *zendeskClientId = [LocalizationManager zendeskClientId];
    if (zendeskAppId) {
        [[ZDKConfig instance] initializeWithAppId:zendeskAppId zendeskUrl:zendeskURL ClientId:zendeskClientId onSuccess:^{
            NSLog(@"Zendesk initialize succes");
        } onError:^(NSError *error) {
            NSLog(@"Zendesk initialize Error:%@",error);
        }];
        [ZDKRequests configure:^(ZDKAccount *account, ZDKRequestCreationConfig *requestCreationConfig) {
            requestCreationConfig.additionalRequestInfo = [NSString stringWithFormat:@"%@%@",
                                                           [requestCreationConfig contentSeperator],
                                                           [self additionalInfo]];
        }];
    }
}


- (void)pushHelpcenterViewControllerOnNavigationController:(UINavigationController *)navigationController
{
    [ZDKConfig instance].userLocale = [[NSBundle mainBundle].preferredLocalizations firstObject];

    [[ZDKSupportView appearance] setNoResultsFoundLabelFont:[UIFont fontWithName:FontNameRegular size:14.0f]];
    [[ZDKSupportArticleTableViewCell appearance] setArticleParentsLabelFont:[UIFont fontWithName:FontNameRegular size:14.0f]];
    [[ZDKSupportArticleTableViewCell appearance] setTitleLabelFont:[UIFont fontWithName:FontNameRegular size:16.0f]];
    [[ZDKSupportTableViewCell appearance] setTitleLabelFont:[UIFont fontWithName:FontNameRegular size:14.0f]];

    [ZDKHelpCenter setNavBarConversationsUIType:ZDKNavBarConversationsUITypeNone];
    if([UIDevice currentDevice].systemVersion.floatValue >= 8.0) {
        [[UINavigationBar appearance] setTranslucent:NO];
    }
    [ZDKHelpCenter showHelpCenterWithNavController:navigationController];
}
```

Regards

Jens

**Comment by oarrabi** [comment] 2016-02-25 11:46
Hello @jaernouts,

I tried the code you posted. And I cannot reproduce this issue.

Can you tell us what version of iOS is this happening? 
Could you try SDK version 1.5.4.1?

Also, it would be extremely helpful if you could send us a sample app that exercises this issue.

Sorry for not being able to help you more with this, will be waiting your reply.

**Comment by jaernouts** [comment] 2016-03-01 13:54
I tried with the latest version and I still have the same issue, but while creating a small demo application I think I discovered the issue. I think it's due to the UITabBarController I'm using, since I didn't have this issue when I used only a UINavigationController. When I added the UITabBarController again, I did have this issue. Is this information good enough or do you want me to upload my example app?

**Comment by oarrabi** [comment] 2016-03-01 16:51
Hello @jaernouts,

Thank you for the additional info. I can reproduce it now. I created a new issue in our backlog to track this. I will keep this issue open until we resolve the issue and inform you.

Thanks for the info provided :)

**Comment by jaernouts** [comment] 2016-03-29 12:14
Hi! Can you provide me with updated information regarding this issue? Any idea when a fix will be provided? Thx!

**Comment by tecknut** [comment] 2016-03-29 13:16
Hey @jaernouts, we replicated the issue. However the fix above in the thread solves this for us. 

```
- (void)lowerBottomLayoutGuide {

    if ([[ZDKUIViewController topViewController] isKindOfClass:[ZDKUIViewController class]]) {
        [self setLayoutGuide:ZDKLayoutRespectTop onController:(ZDKUIViewController*)[ZDKUIViewController topViewController]];
    }
}

- (void)raiseBottomLayoutGuid {
    if ([[ZDKUIViewController topViewController] isKindOfClass:[ZDKUIViewController class]]) {
        [self setLayoutGuide:ZDKLayoutRespectAll onController:(ZDKUIViewController*)[ZDKUIViewController topViewController]];
    }
}

- (void)setLayoutGuide:(ZDKLayoutGuide)guide onController:(ZDKUIViewController*)controller {
    controller.layoutGuide = guide;
}
```

```
// somewhere before Zendesk SDK stuff happens in your view controller.
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(lowerBottomLayoutGuide) name:UIKeyboardWillShowNotification object:nil];
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(raiseBottomLayoutGuid) name:UIKeyboardWillHideNotification object:nil];
```

```
- (void)dealoc {
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
```

Have you tried the above code in your presenting view controller?

**Comment by jaernouts** [comment] 2016-04-05 04:43
Hi @tecknut, I tried this workaround already but it didn't help. That's also why I reopened this issue, I tried everything that was said before...

Regards!

**Comment by JanJoris** [comment] 2016-05-20 07:29
@tecknut can you guys a have a look at this bug once more, we are still not able to resolve this at our end (and I dislike open tickets for that long). I'm in the same company as @jaernouts btw.

**Comment by tecknut** [comment] 2016-05-24 15:13
Hey @JanJoris we've looked at this a number of times and have not been able to replicate the issue. 

There must be something in your apps setup which we have not replicated. I understand if it's not possible to show us you source, but how would you feel about a Skype call, or Google hangout to try resolve this? We usually don't do this, but considering this has been affecting you for a while maybe it's worth a try.

Alan

**Comment by jaernouts** [comment] 2016-05-25 05:03
@tecknut that contradicts what you (and @oarrabi) said before? @oarrabi said explicitly he you could reproduce it by using UITabBarController in combination with the UINavigationController. That's also the way our app is build. Besides, I don't have this issue with only a UINavigationController...

**Comment by tecknut** [comment] 2016-05-25 10:43
@jaernouts, @oarrabi did say he could reproduce the black area. I took @oarrabi's sample app which reproduced black area, and solved the issue with the code snippets above. See https://github.com/zendesk/zendesk_sdk_ios/issues/114#issuecomment-202888257 

This is why I said there must be something with your app setup which we have not replicated ( https://github.com/zendesk/zendesk_sdk_ios/issues/114#issuecomment-221303437 ) which is causing the issue.

Do you want to try work together on this issue in a call?

**Comment by baz8080** [comment] 2016-10-06 09:17
Closing this issue because it has been a while since any activity on it.

**Closed by baz8080** 2016-10-06 09:17 UTC
Labels: bug

**Comment by arorapulkit** [comment] 2017-03-22 22:05
<img width="487" alt="screen shot 2017-03-23 at 3 06 02 am" src="https://cloud.githubusercontent.com/assets/14070166/24222858/9837574e-0f79-11e7-969b-3c075668c54d.png">

I'm facing this issue in Zendesk SDK (1.7.6.1). I tried the above solution but did not work for me.

**Comment by mathewcropper** [comment] 2017-03-23 08:59
Hi @arorapulkit. Please could you try this on the latest version of the Support SDK (v1.9.1.1) and let me know if you are having the same problem? I'm running the latest version of the Support SDK on iOS 10.2.1 and am unable to reproduce this.
