### ISSUE TITLE
"zd_dispatcher_err" = "HTTP Error: 450"

### ISSUE THREAD

**Issue by ericlewis** [zendesk/zendesk_sdk_ios#49] opened 2015-07-28 00:19 UTC
no clue what this means...followed the directions and we get this every time, even though setup is a success.

**Comment by tecknut** [comment] 2015-07-28 10:09
@ericlewis can you provide a bit more information? At what point do you get this error? This is usually when a client id is incorrect. 

If the client id and app id are correct and match the app config in the SDK admin page it might be best to open a ticket with support.zendesk.com and give this issue as a reference in the ticket. Don't paste your client id and app id here.

**Comment by ericlewis** [comment] 2015-07-28 15:10
We get this after properly setting up our client ID directly from your own code to copy and paste. Then we setup an identity after the success works, then show the UI for sending a message. Try sending a message and then it just doesn't work. We have tried to arrange it in all sorts of ways too, even using your example apps. Ours only returns 450s the moment we actually try sending a ticket from the client. 



—

**Comment by tecknut** [comment] 2015-07-30 09:40
@ericlewis Can you open this as a ticket with us on https://support.zendesk.com/ please? We will need to have access to your account to debug this issue.

**Comment by kmiloaguilar** [comment] 2015-08-01 03:11
I got this messaged when trying to send a new ticket without setting user information. I'm using anonymous authentication for user.

**Comment by tecknut** [comment] 2015-08-10 09:37
@kmiloaguilar Are you still having this issue?

**Comment by kmiloaguilar** [comment] 2015-08-10 13:23
Yes got that, but I was still not setting info for anonymous user. It was my mistake.

**Comment by tecknut** [comment] 2015-08-10 13:27
@kmiloaguilar Ok, thanks for getting back to us.

@ericlewis Are you still getting this error?

**Comment by tecknut** [comment] 2015-08-19 15:01
@ericlewis just bumping this to see if the issue is solved for. Can you let us know, otherwise we'll be closing issue soon.

**Comment by tecknut** [comment] 2015-09-15 13:47
Closing this.

**Closed by tecknut** 2015-09-15 13:47 UTC

**Comment by simonmitchell** [comment] 2017-03-27 15:24
I'm still getting this issue @tecknut. I've set up an anonymous user and all the API config is correct. I can even po the shared user and it's configured fine.

`
ZDKAnonymousIdentity *identity = [ZDKConfig instance].userIdentity;
identity.name = name;
identity.email = email;
// I've set a breakpoint here for my po
[ZDKConfig instance].userIdentity = identity;

[ZDKRequests presentRequestCreationWithViewController:controller];
`

Get this from po, which is of class ZDKAnonymousIdentity
`
{
    email = "simon@3sidedcube.com";
    name = "Simon Mitchel";
    "sdk_guid" = "0D2A7338-9575-4496-948F-ED8FFC14CE52";
}
`

**Comment by Jholman8** [comment] 2017-04-20 19:00
Having the same issue. Anyone find a solution?

**Comment by tecknut** [comment] 2017-04-21 10:05
@simonmitchell @Jholman8 Can you both confirm that your appId clientId and url are all correct and match what is in the settings panel in your Zendesk instance?

This is generally an issue with incorrect details provided at SDK initialisation, so it's worth double checking this.

**Comment by simonmitchell** [comment] 2017-04-24 10:10
@tecknut it turned out our issue was simply that the project manager adding the App had forgotten to hit the "Done" (Or whatever it reads) button to finish adding the app to our account. Really it should be returning a better error in this case, or you shouldn't provide us with a cliendId or appId until the app has actually been added to the ZenDesk account :P

**Comment by joaogouveia89** [comment] 2018-04-20 14:40
Having the same issue. 

I'm initializing the SDK like

ZendeskConfig.INSTANCE.init(this,
                ZENDESK_URL,
                APP_ID,
                OAUTH_CLIENT_ID);

Identity identity = new AnonymousIdentity.Builder()
                .withNameIdentifier(name)
                .withEmailIdentifier(email)
                .build();

ZendeskConfig.INSTANCE.setIdentity(identity);

RequestProvider requestProvider = ZendeskConfig.INSTANCE.provider().requestProvider();
        CreateRequest request = new CreateRequest();
        request.setSubject("My printer is on fire!");
        request.setDescription("The smoke is very colorful.");
        request.setTags(Arrays.asList("printer", "fire"));

        requestProvider.createRequest(request, new ZendeskCallback<CreateRequest>() {
            @Override
            public void onSuccess(CreateRequest createRequest) {
                Log.i("ZENDESK", "REQUEST DEU CERTO");
            }

            @Override
            public void onError(ErrorResponse errorResponse) {
                Log.i("ZENDESK", "REQUEST DEU ERRO: {\n" +
                        "getReason = " + errorResponse.getReason() + "\n" +
                        "getResponseBody = " + errorResponse.getResponseBody() + "\n" +
                        "getResponseBodyType = " + errorResponse.getResponseBodyType() + "\n" +
                        "url = " + errorResponse.getUrl() + "\n" +
                        "status = " + errorResponse.getStatus());
            }
        });


This is exactaly what I'm trying to input in this sequence. What I'm doing wrong?

**Comment by xanexpt** [comment] 2018-05-15 15:11
any news about this issue? I'm also getting http 450 when trying to submit a new support ticket
