### ISSUE TITLE
Orientation for Attachments

### ISSUE THREAD

**Issue by saraswatayu** [zendesk/zendesk_sdk_ios#185] opened 2016-05-27 18:12 UTC
Issue: Let's say I have an app that runs only in landscape. But in order to satisfy the issue of the app running in portrait for attachments to work, I've created a navigation controller that is locked into portrait mode. The navigation controller is then modally presented, forcing the app to be in the portrait orientation I desired. The same debugging message still pops up:
`Application must support UIInterfaceOrientationPortrait for attachments to work`

Shouldn't the attachments button in the Create Request and Ticket Detail views still appear?

**Comment by oarrabi** [comment] 2016-05-30 12:27
Hello @saraswatayu 

I have tried to reproduce your issue but I cannot reproduce it at this time. Hiding the button for landscape only app is a little tricky so we have issues normally reproducing the issues. 

Would you please provide me more info regarding it:
On what iOS device is this issue happening?
Which version of the SDK does this happen on?

It would be great if you provide a sample app that reproduces this issue.

Thanks :)

**Comment by RonanMcH** [comment] 2016-07-05 15:38
Hi @saraswatayu ,
Have you got anymore feedback for us on this issue? 
Ronan.

**Comment by oarrabi** [comment] 2016-07-13 11:09
Hello @saraswatayu,

I will close this issue for now, please don't hesitate to reopon it if in case it's still occurring .

Thanks :)

**Closed by oarrabi** 2016-07-13 11:09 UTC
Labels: pending information
