### ISSUE TITLE
Filtering Help center by Category ID works intermittently

### ISSUE THREAD

**Issue by jelenadj** [zendesk/zendesk_sdk_ios#219] opened 2016-09-06 11:51 UTC
I am using:
```
+ (void) pushHelpCenterWithNavigationController:(UINavigationController *)navController
                             filterByCategoryId:(NSString *)categoryId
                                   categoryName:(NSString *)categoryName
                                    layoutGuide:(ZDKLayoutGuide)aGuide

```
and I am getting sections from the selected category properly displayed, however, I am often getting "Failed to get sections" using the same code. Any idea?

**Comment by schlan** [comment] 2016-09-06 12:21
Hi @jelenadj, can you activate logging and send us the generated logs when the issue is happening? 
https://developer.zendesk.com/embeddables/docs/ios/advancedtopics#logging

**Comment by jelenadj** [comment] 2016-09-06 12:32
@schlan I just reproduced it, it seems that I am getting 404 when I try to retrieve sections, and URL used by SDK is:
"v2/help_center/(null)/categories/200291128/sections.json?per_page=1000"
seems that language code is used as (null) instead as "en-US" for example, if it's not specified, or if it's wrong. Btw, my current preferred language is set as "en" not as "en-US".

**Comment by jelenadj** [comment] 2016-09-06 14:12
@schlan Full zendesk log is attached.
[zendesk_log.txt](https://github.com/zendesk/zendesk_sdk_ios/files/456890/zendesk_log.txt)

**Comment by schlan** [comment] 2016-09-06 14:50
Hi @jelenadj to confirm, did you enabled Help Center on Mobile SDK settings page in your Zendesk instance?

**Comment by jelenadj** [comment] 2016-09-06 14:53
Yes, Help Center is enabled on Settings > Mobile SDK > My App > Customization. Sometimes it fails to load sections, and sometimes everything works as expected (using the same Zendesk configuration and device/app).

**Comment by schlan** [comment] 2016-09-06 15:06
Thanks for clarifying. We need to look into that issue more closely, can you please open a ticket with us at support@zendesk.com ?

**Comment by jelenadj** [comment] 2016-09-06 15:21
Just opened a ticket. Btw, I am not completely sure, but seems that I can't reproduce this issue using previous version v1.6.2.1.

**Comment by jelenadj** [comment] 2016-09-06 18:47
Now, I can reproduce it every time. First opening of filtered help center is unsuccessful (404, because of invalid URL), but when I open it next time (without restarting the app), URL is correctly formatted. So, only first attempt of pushHelpCenterWithNavigationController fails.

**Comment by lightbow** [comment] 2016-09-08 01:18
Same thing with me. Started happening on my builds with the latest version, but not present in my shipping app (which uses 1.6.2.1). On a clean install, the first visit to the help center fails, and doesn't load no matter how many times I hit the "Retry" button. If I leave and come back however, everything appears fine.

**Comment by ianthetechie** [comment] 2016-09-09 03:45
I can confirm this is an issue for me as well using SDK 1.7.0.1 and higher. Exactly as @lightbow stated, it fails (with a 404 code for me) on the first try. The retry button also fails to load. Backing out (presenting using a navigation controller) and relaunching help center works every time.

My client would really like to upgrade to the 1.7.x branch to (finally!) get a loading indicator when the Help Center is taking a while to render a page, but it seems we'll have to hold off until this is fixed.

**Comment by RonanMcH** [comment] 2016-09-09 09:05
Hi @jelenadj , @lightbow  and @ianthetechie ,
We have identified the issue with the `null` entry where `locale` should be in the request for Help Center sections.  The issue has been fixed and it will be in our next release. We will update this thread once it has been released.
Thanks,
Ronan.

**Comment by sspitzer** [comment] 2016-09-09 22:48
We had the same problem.  Our hack until the next release:  a custom NSURLProtocol to rewrite the request, fixing the (null).

For more on how to do that, see https://www.raywenderlich.com/59982/nsurlprotocol-tutorial

**Comment by tecknut** [comment] 2016-09-13 08:57
@jelenadj @sspitzer @lightbow We released a patch yesterday which fixed this issue. I'm closing this, please get in touch if you have further issues.

**Closed by tecknut** 2016-09-13 08:57 UTC
Labels: bug, help wanted
