### ISSUE TITLE
buttons disappear on Contact Form when iPhone is rotated

### ISSUE THREAD

**Issue by andrewljohnson** [zendesk/zendesk_sdk_ios#143] opened 2016-02-04 05:58 UTC
Here's a video of the bug: https://www.dropbox.com/s/djugsku2f0g8q89/zd-bug.mov?dl=0

The nav bar buttons disappear after a rotate and re-rotate.

I added the view this way:

    self.navigationController.modalPresentationStyle = UIModalPresentationFormSheet;
    [ZDKHelpCenter showHelpCenterWithNavController:self.navigationController
                              filterByCategoryId:@"FOO"
                                    categoryName:HELP_WORD
                                     layoutGuide:ZDKLayoutRespectAll];

**Comment by brendan-fahy** [comment] 2016-02-04 14:39
Hi @andrewljohnson 

We've been unable to reproduce this behaviour so far. Can you give us any more detail on how to do so? Have you tried resetting your simulator to see if that made a difference?

Regards,

Brendan

**Comment by andrewljohnson** [comment] 2016-02-04 20:39
I've had two colleagues reproduce this on testflight builds of the app on
iPhones.

Let me know if you think someone in our code could have this effect? I
thought I was using the SDK in the standard way.

Andrew Johnson
Founder
*gaiagps.com <http://gaiagps.com>*

**Comment by RonanMcH** [comment] 2016-02-09 13:28
Hi @andrewljohnson,
We still can't recreate this issue so we have opened a ticket for you with us so that we may continue solving this problem internally.  
Thanks,
Ronan.

**Comment by andrewljohnson** [comment] 2016-02-19 23:46
I don't know what else to do. I can still reproduce this bug with the latest SDK: Using ZendeskSDK (1.5.4.1)

**Comment by baz8080** [comment] 2016-02-23 14:40
@andrewljohnson did you see the ticket that Ronan made for you on February the 9th? We need more info from you in order to try to reproduce this problem.

**Comment by andrewljohnson** [comment] 2016-02-27 04:34
Ronan said: "In order to recreate the problem you are experiencing could you send us any code that may be effecting your navigation bar and we can begin debugging the problem?"

I'm not sure what's being asked for.

**Comment by RonanMcH** [comment] 2016-02-29 09:37
Hi @andrewljohnson ,
Sorry if I was unclear. Could you send us a small sample project with the problem recreated in it via the ticket we opened for you? Currently, we cannot recreate this internally and therefore can't fix it for you.
Thanks,
Ronan.

**Comment by andrewljohnson** [comment] 2016-02-29 18:59
This would be time consuming, I will put it on my list and maybe do it
sometime.

This would be easier if the Zendesk SDK was open source, then I could just
fix it without having to generate a new xcode project. Most of the SDKs we
use (e.g. MixPanel, Segment, UserVoice) are open source.

When I asked about the open source issue, I wad told it was discussed
internally, but I wasn't given any reasoning for why this SDK is closed
source. That would be cool to know too, and hopefully to get some timeline
when the SDK will be open sourced.

**Comment by oarrabi** [comment] 2016-03-01 10:47
Hello @andrewljohnson,

We are still planning to Open source the SDK. However, in order to do so, we need to have some internal alteration on the SDK for it to be ready. After we knock off these issues, we are going to open source it. 

At the moment, we don't have a definite timeline for when this is happening. For the time being, since we are not able to reproduce this bug, it would be great to have a sample app that exercise this issue. Sorry for the inconvenience.

**Comment by andrewljohnson** [comment] 2016-03-01 19:47
It's on my todo list at least...

FWIW, without actually testing it, I have some suspicion its related to this library: https://github.com/John-Lluch/SWRevealViewController

I'd probably try and build a test case with that view controller. My only evidence for this is:

 * it doesn't occur on iPad
 * I've had issues with this lib before

**Comment by RonanMcH** [comment] 2016-07-05 13:04
Hi @andrewljohnson , 
Have you managed to reproduce this issue in a sample app yet?
Thanks,
Ronan.

**Comment by oarrabi** [comment] 2016-07-13 11:08
Hello @andrewljohnson,

I will close this issue for now, please don't hesitate to reopon it if in case it's still occurring .

Thanks :)

**Closed by oarrabi** 2016-07-13 11:08 UTC
Labels: bug, pending information
