### ISSUE TITLE
ZDKRequestProvider crash

### ISSUE THREAD

**Issue by sahara108** [zendesk/zendesk_sdk_ios#136] opened 2015-12-22 07:46 UTC
Here is how I add attachment into a support request:

           let zdkUploader = ZDKUploadProvider()
           let anonymousIdentity = ZDKAnonymousIdentity()
           anonymousIdentity.externalId = "An Identifier"
           ZDKConfig.instance().userIdentity = anonymousIdentity
           MBProgressHUD.showHUDAddedTo(self.navigationController?.view, animated: true)
           zdkUploader.uploadAttachment(UIImageJPEGRepresentation(image, 0.5), withFilename: fileName, andContentType: "image/jpeg") { (response, error) -> Void in
            MBProgressHUD.hideHUDForView(self.navigationController?.view, animated: true)
            if error == nil {
                ...
                self.attachments.append(att)
                self.tableView.reloadData()
            }
        }

And post the request
        let anonymousIdentity = ZDKAnonymousIdentity()
        
        anonymousIdentity.email = email
        anonymousIdentity.name = name
        anonymousIdentity.externalId = "An Identifier"
        
        // Anonymous Auth
        ZDKConfig.instance().userIdentity = anonymousIdentity
        
        // Submit request here!
        let provider = ZDKRequestProvider()
        
        let request = ZDKCreateRequest()
        
        request.subject = subject
        request.requestDescription = issueDescription
        
        for imageAtt in self.attachments {
            request.attachments.append(imageAtt.uploadResponse.uploadToken)
        }

<img width="1004" alt="screen shot 2015-12-22 at 2 42 23 pm" src="https://cloud.githubusercontent.com/assets/1707951/11950375/669cbca0-a8ba-11e5-9879-1ce20ad88a75.png">

**Comment by oarrabi** [comment] 2015-12-23 18:36
Hi @sahara108, the issue is around
```
request.attachments.append(imageAtt.uploadResponse.uploadToken)
```
`request.attachments` holds a list of `ZDKUploadResponse` and not of strings. Could you please to try to edit the above snippet to:

```
request.attachments.append(imageAtt.uploadResponse)
```

Please let me know if this solves your issue.

**Comment by sahara108** [comment] 2015-12-24 01:37
Oops!. It is documented as: 
           /**
     *  List of upload tokens.
     *
     *  @since 1.3.0.1
     */
    public var attachments: [AnyObject]!
So I use `uploadToken`.

It works now. THanks

**Comment by oarrabi** [comment] 2015-12-25 16:48
Happy to hear that it works for you, closing this :)

**Closed by oarrabi** 2015-12-25 16:48 UTC
Labels: question
