### ISSUE TITLE
ZDKCustomField Integer literal overflows when stored into 'Int'

### ISSUE THREAD

**Issue by smoi** [zendesk/zendesk_sdk_ios#332] opened 2017-10-17 11:12 UTC
- SDK version: 1.1.11.1
- Xcode version: 9
- iOS or Simulator: iOS 11
- iOS Version: iOS 11
- Swift version: 3

I'm creating a custom request using ZDKRequestProvider, in this request I want to add some custom fields that i created on Zendesk. When I try on the simulator the fields are not sent. If I build the app for archiving or device I get this error 

Integer literal '114100117231' overflows when stored into 'Int'

And this is how I create the custom field param

let text = ZDKCustomField(fieldId: NSNumber(value: 114100117231), andValue: bookText)

I've tried both using an NSNumber or just the id

**Comment by tecknut** [comment] 2017-10-19 08:58
Hey @smoi, 

I tried the following code to see if I could get the field id to overflow: 

```
let text = ZDKCustomField(fieldId: NSNumber(value: 114100117231), andValue: "bookText")
dump(text?.dictionaryValue())
```

When I run this I get the following output:

```
Optional([AnyHashable("id"): 114100117231, AnyHashable("value"): bookText])
  ▿ some: 2 key/value pairs
    ▿ (2 elements)
      ▿ key: AnyHashable("id")
        - value: "id"
      - value: 114100117231 #0
        - super: NSNumber
          - super: NSValue
            - super: NSObject
    ▿ (2 elements)
      ▿ key: AnyHashable("value")
        - value: "value"
      ▿ value: bookText #1
        - super: Swift._SwiftNativeNSString
          - super: _SwiftNativeNSStringBase
            - super: NSString
              - super: NSObject
        ▿ _core: Swift._StringCore
          ▿ _baseAddress: Optional(0x000000010ba2eddc)
            ▿ some: 0x000000010ba2eddc
              - pointerValue: 4490194396
          - _countAndFlags: 8
          - _owner: nil
```

The value doesn't seem to be overflowing at runtime. 

Can you give us some more context please? The rest of your code for adding a custom field to a request?

Thanks,
Alan

**Comment by smoi** [comment] 2017-10-19 10:46
Hello Alan,

the code doesn't even compile. It works fine if I compile for Simulator but when I try to compile for device I have that error. Here's a screenshot [http://bit.ly/2invTW5](url)

What version of xcode are you using?

**Comment by tecknut** [comment] 2017-10-19 21:01
I'm using Xcode 9. It compiles, runs and prints in the debugger.

That link won't load for me, can you attach a screen shot to the comment itself?

Thanks,
Alan

**Comment by smoi** [comment] 2017-10-19 21:02
Here it is
<img width="797" alt="xx" src="https://user-images.githubusercontent.com/635718/31794155-924fa87e-b521-11e7-99d1-b72d95f1edd3.png">

**Comment by tecknut** [comment] 2017-10-19 21:04
Thanks, can you try add the SDK to an empty project? If the error happens there then send on the project in a zip and I'll try it here to see if get the error. 
Alan

**Comment by divo** [comment] 2017-10-24 14:25
@smoi Can you check your projects valid archs? I was able to reproduce this by archiving a project with armv7 support. Since only 64 bit architectures are supported by Apple it is safe to remove support for 32 bit devices.

**Comment by kleiberjp** [comment] 2017-11-05 11:54
i'm having the same issue for some custom fields... any solution?

**Comment by baz8080** [comment] 2017-11-06 11:50
@kleiberjp armv7 and armv7s are 32-bit architectures. Can you remove them as suggested in https://github.com/zendesk/zendesk_sdk_ios/issues/332#issuecomment-339008266

**Comment by baz8080** [comment] 2017-11-16 11:31
I'm going to close this issue for now. Please feel free to reopen if you're still having an issue.

**Comment by devKC** [comment] 2017-11-30 02:45
@baz8080 I'm seeing this issue too. What was the recommended solution? I feel like the solution should work for 32-bit as well.

**Comment by arshiacont** [comment] 2017-12-02 10:00
The suggested solution for removing armv7 and armv7s means that we should drop support for _iPhone 5_ and _iPhone5c_ (let's forget about older ones!). Do you really think this is an acceptable solution?! Check https://fiksu.com/resources/ios_trackers/#iphones-usage

**Comment by baz8080** [comment] 2017-12-04 14:21
We've re-opened the issue. We'll try to find a workaround for you.

**Comment by arshiacont** [comment] 2017-12-04 14:24
Until this is solved, a work around would be to wrap calls to `ZDKCustomField` in preprocessing macros mentioning architectures and avoiding custom fields on 32 bit devices:

<code>
        #if arch(arm64) || arch(x86_64)
		ZDKCustomFields…
	#endif
</code>

**Comment by volatilegg** [comment] 2017-12-12 12:55
This workaround works for me so far:
```swift
let doubleValue: Double = 114100117231
let fieldId: NSNumber = NSNumber(value: doubleValue)
let field = ZDKCustomField(fieldId: fieldId, andValue: "foo bar")
```

**Comment by arshiacont** [comment] 2017-12-12 13:53
Interesting! Thanks for sharing. And I assume that you receive the info on Zendesk backend?

If yes, this can be considered a fix!

**Comment by volatilegg** [comment] 2017-12-12 14:41
@arshiacont Yes, there's no error from Zendesk backend for me so far.

**Comment by divo** [comment] 2018-05-10 10:02
Going to close this. The SDK API is correct, and the compiler won't accept an integer literal if it is longer than 32 bits. The compiler needs a little hint to use the correct type.

**Closed by divo** 2018-05-10 10:02 UTC

**Comment by chaseacton** [comment] 2018-06-08 17:02
Please fix this in your documentation: https://developer.zendesk.com/embeddables/docs/ios_support_sdk/help_center#filter-articles-by-category
