### ISSUE TITLE
Using Contact Us form, tapping "attachment" button crashes app

### ISSUE THREAD

**Issue by ehlersd** [zendesk/zendesk_sdk_ios#233] opened 2016-09-26 03:34 UTC
- SDK version: 1.7.4.1
- Xcode version: 8.0
- iOS or Simulator: iPhone 6 device
- iOS Version: iOS 9.3.5
- Swift version: Obj-C

Steps to Reproduce:
1.  In HelpCenter, tap "Contact Us" (upper-right)
2. Tap "New" (upper-right)
3. Tap attachment icon (lower-left)
4. Tap "Choose existing" or "Take a photo"
5. App crashes:

**\* Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UITableView.m:1716

I DO see two warnings before this one, that are the same:

2016-09-25 22:30:01.776 PocketBrew[3584:3012277] [DEBUG]: Application must support UIInterfaceOrientationPortrait for attachments to work

And the device is currently in Portrait mode.

**Comment by roelspruit** [comment] 2016-09-26 14:35
I also just ran into this issue but with a different version:

- SDK 1.7.3.1
- Xcode 8.0
- iPhone 6 plus
- iOS 10.0.1

**Comment by roelspruit** [comment] 2016-09-26 14:44
My bad, I just found out I forgot to do this step of the SDK integration: https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk#update-usage-descriptions-in-info.plist

Maybe this also fixes it for you?

**Comment by ehlersd** [comment] 2016-09-26 15:30
No, not my issue.  I already have camera/photo library access enabled in the app, so these usage descriptions already had to be in place...

But thanks for the suggestion!

**Comment by mathewcropper** [comment] 2016-09-26 15:34
Hey @roelspruit! I wasn't able to repro this. Were you able to do this with a device connected and [logging enabled](https://developer.zendesk.com/embeddables/docs/ios/debug)? I'm curious to see what comes out in the logs.

**Comment by ehlersd** [comment] 2016-09-26 15:59
@mathewcropper Were you talking to @roelspruit or myself?  I believe @roelspruit resolved his error...

**Comment by mathewcropper** [comment] 2016-09-26 16:01
Sorry.. my bad! I did mean you, @ehlersd.

**Comment by ehlersd** [comment] 2016-09-26 16:10
LOL, No worries.

The only thing I noticed in the logs was the Assertion and the 2 warnings above (and other items relating to localization strings).

Give me an hour or so and I'll hook up and run the test again and send you the details.

**Comment by mathewcropper** [comment] 2016-09-27 09:32
You rock! Thanks @ehlersd.

**Comment by ehlersd** [comment] 2016-09-27 15:04
@mathewcropper Sorry, yesterday completely got away from me.

Here's the last of the console log:

2016-09-27 10:02:01.132 PocketBrew[3781:3267050] [DEBUG]: Successfully updated SDK settings
2016-09-27 10:02:01.137 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.rightBarButton.title.contact" = "Contact us";
2016-09-27 10:02:01.141 PocketBrew[3781:3267050] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2016-09-27 10:02:01.142 PocketBrew[3781:3267050] [DEBUG]: Adding auth to request [0x128b6e7d0]: https://pocketbrew.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
2016-09-27 10:02:01.142 PocketBrew[3781:3267050] [DEBUG]: About to execute [0x12755bb70]: https://pocketbrew.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
with headers
{
    Accept = "application/json";
    Authorization = "Bearer 220392320f4566ad99bacc12ba46ff8c894b74c1a3a5a83da078172ceba2146e";
    "Client-Identifier" = "mobile_sdk_client_ae7a2c14d09f623063ee";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "CAC44F58-2083-46C2-88D7-77227BC13775";
    "User-Agent" = "Zendesk-SDK/1.7.4.1 iOS/9.3.5 Env/Development";
}
2016-09-27 10:02:01.806 PocketBrew[3781:3267050] [DEBUG]: Response code [0x12755bb70]: 200
2016-09-27 10:02:01.807 PocketBrew[3781:3267050] [DEBUG]: Request success: [0x12755bb70]: https://pocketbrew.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
2016-09-27 10:02:03.283 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.requestList.title" = "My tickets";
2016-09-27 10:02:03.290 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.rightBarButton.title.new" = "New";
2016-09-27 10:02:03.824 PocketBrew[3781:3267050] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2016-09-27 10:02:03.826 PocketBrew[3781:3267050] [DEBUG]: SDK configuration file found in local storage
2016-09-27 10:02:03.831 PocketBrew[3781:3267050] [DEBUG]: SDK configuration file found in local storage
2016-09-27 10:02:03.833 PocketBrew[3781:3267050] [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
2016-09-27 10:02:03.833 PocketBrew[3781:3267050] [WARNING]: __74-[ZDKRequestProvider getAnonymousRequestsWithTokens:byStatus:withCallack:]_block_invoke.249 There are no requests to fetch
2016-09-27 10:02:03.842 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.requestList.empty" = "No tickets currently open";
2016-09-27 10:02:04.625 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.cancel.button" = "Cancel";
2016-09-27 10:02:04.626 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.submit.button" = "Send";
2016-09-27 10:02:04.631 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.title" = "Contact us";
2016-09-27 10:02:04.633 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.description.placeholder" = "Description";
2016-09-27 10:02:04.733 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.email.placeholder" = "Your email address";
2016-09-27 10:02:05.286 PocketBrew[3781:3267050] [DEBUG]: SDK configuration file found in local storage
2016-09-27 10:02:07.626 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.sdk.ZDKRequests.createRequest.attachment.chooseExisting" = "Choose existing";
2016-09-27 10:02:07.627 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.sdk.ZDKRequests.createRequest.attachment.newPhoto" = "Take a photo";
2016-09-27 10:02:07.628 PocketBrew[3781:3267050] [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.cancel.button" = "Cancel";
2016-09-27 10:02:09.824 PocketBrew[3781:3267050] [DEBUG]: Application must support UIInterfaceOrientationPortrait for attachments to work
2016-09-27 10:02:09.825 PocketBrew[3781:3267050] [DEBUG]: Application must support UIInterfaceOrientationPortrait for attachments to work
2016-09-27 10:02:09.825 PocketBrew[3781:3267050] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UITableView.m:1716

**Comment by mathewcropper** [comment] 2016-09-27 16:34
Thanks! I was hoping for a 'the logs contain the answer' situation, but no luck there.

Leave this with us. We'll look into it and try to figure out what's going on here.

PS: I edited your post to remove some info. Hope you don't mind.

**Comment by ehlersd** [comment] 2016-09-27 17:57
@mathewcropper Oops....no, don't mind at all.

**Comment by schlan** [comment] 2016-09-28 13:35
Hi @ehlersd, we weren't able to replicate your issue, we would need some further information to continue working on it. Can you please provide:

- Screenshot of the create ticket screen, before pressing the attachment button.
- The exact exception breakpoints 
- Screenshot after the crash happened

**Comment by ehlersd** [comment] 2016-10-05 01:31
Sure thing....

Here's the screenshot of the exact breakpoint details/log...

![screenshot 2016-10-04 20 23 13](https://cloud.githubusercontent.com/assets/2302997/19098183/d7d6b1d0-8a70-11e6-8999-054a3a168d33.png)

Here's the screenshot of the device prior to tapping the attachment button:

![2016-10-04 20 22 43](https://cloud.githubusercontent.com/assets/2302997/19098252/5ba41886-8a71-11e6-993f-9d6313a81884.png)

Here's the screenshot of the device after tapping the attachment button (but before the crash):

![2016-10-04 20 22 52](https://cloud.githubusercontent.com/assets/2302997/19098263/6c25e9dc-8a71-11e6-9332-0734405a7c7c.png)

And here's the screenshot of the device after the crash occurred:

![2016-10-04 20 23 22](https://cloud.githubusercontent.com/assets/2302997/19098272/7a6cb5a2-8a71-11e6-9755-892a6ec784c4.png)

**Comment by StevenDiviney** [comment] 2016-10-05 14:56
@ehlersd We are still trying to figure this out. What are your apps supported orientations and how are you specifying them? We may need to open a ticket for you in Zendesk and ask for more detail. This is proving tough to figure out.

**Comment by ehlersd** [comment] 2016-10-05 21:35
It's solely Portrait (for iPhone) at the moment, but it's also a Universal app and the iPad supports all orientations.

Of course, my current testing with this has only been on the iPhone in Portrait.

**Comment by ehlersd** [comment] 2016-10-06 20:41
@StevenDiviney Please let me know if there is anything I can do to help diagnose/debug this crash.

**Comment by tecknut** [comment] 2016-10-06 21:05
Hey @ehlersd could you tell us which way you've configured you project in relation to device orientation?

These logs:

```
Application must support UIInterfaceOrientationPortrait for attachments to work
```
shouldn't be printing if you're app is in portrait. Our main issue is not being able to replicate this. It would be supper helpful if we were able to configure a test project here in the same way you've done with your's.

We're based in Ireland, so it'll be morning time here before we get around to working on this.

Thanks

**Comment by ehlersd** [comment] 2016-10-06 21:15
@tecknut I've configured the Portrait only in the Project->General tap under Deployment Info (iPhone).  I guess that is what you are referring to.

**Comment by ehlersd** [comment] 2016-10-06 21:45
And I just confirmed that it's crashing also on the iPad.

**Comment by oarrabi** [comment] 2016-10-11 13:30
Hello @ehlersd,

We are still unable to reproduce it. We are still going to try to reproduce it.
Would it be possible for you to provide us with a sample app that shows this error, that would helps us a lot?

Thanks :)

**Comment by RonanMcH** [comment] 2017-05-09 12:41
Hello @ehlersd ,
Just checking in since we have not heard from you in a while. Is this still an issue for you?
Thanks,
Ronan.

**Comment by afehners** [comment] 2017-05-10 11:21
I had this issue. It turned out it was due to a missing info.plist entry to explain why my app needed access to the users photo library. Might not be the same issue here but adding this fixed it and stopped the crashing:

<key>NSCameraUsageDescription</key>
<string>Used to assign a picture to a support request</string>

and

<key>NSPhotoLibraryUsageDescription</key>
<string>Used to an image to a support request.</string>

**Comment by baz8080** [comment] 2017-08-16 10:01
I'm going to close this issue for now.

**Closed by baz8080** 2017-08-16 10:01 UTC
Labels: bug
