### ISSUE TITLE
My tickets modal has no cancel/dismiss button. 

### ISSUE THREAD

**Issue by markst** [zendesk/zendesk_sdk_ios#107] opened 2015-10-29 05:05 UTC
![screen shot 2015-10-29 at 16 04 27](https://cloud.githubusercontent.com/assets/274318/10810626/d1e3f4c6-7e56-11e5-9a79-91c7022618de.png)

**Comment by StevenDiviney** [comment] 2015-10-29 10:23
Hey @markst 

What methods are using to present this view? Is it showRequestListWithNavController? Can you try presentRequestListWithNavController? Thanks.

**Comment by baz8080** [comment] 2015-11-13 11:55
@markst Did you get a chance to test this as per the comment above?

**Comment by RonanMcH** [comment] 2015-11-23 13:53
Hi @markst ,
I am going to tentatively close this issue since you have not responded. Feel free to reopen it if you are still experiencing problems.
Ronan.

**Closed by RonanMcH** 2015-11-23 13:53 UTC

**Comment by lilyghukasyan** [comment] 2015-12-03 14:02
Hi,

I have the same issue on iPhone app (on iPad "Cancel" button is displayed):
![simulator screen shot dec 3 2015 5 48 55 pm](https://cloud.githubusercontent.com/assets/5071229/11562239/cf0dcf72-99dd-11e5-9ba2-ae5927300302.png)

I use presentRequestListWithNavController: method. 
It's easy to reproduce the issue in the Sample app > ZDSampleViewController > requestListView, if you change showRequestListWithNavController: to presentRequestListWithNavController: and run on iPhone.

thanks.

**Comment by markst** [comment] 2016-02-26 04:29
this is my resolution for this:

```objc
- (IBAction)supportButtonTouchedUpInside:(id)sender
{
    self.userDidTapSupport = YES;
    
    if ([self.sideMenuViewController.contentViewController isKindOfClass:[UINavigationController class]]) {
        @try {
            UINavigationController * nav = (id)self.sideMenuViewController.contentViewController;
            [ZDKRequests showRequestCreationWithNavController:nav];
            
            //Resolution for issue https://github.com/zendesk/zendesk_sdk_ios/issues/107
            if ([nav.presentedViewController isKindOfClass:[UINavigationController class]]) {
                UIViewController * vc = [(UINavigationController *)nav.presentedViewController topViewController];
                [vc.navigationItem setLeftBarButtonItem:[[UIBarButtonItem alloc] initWithTitle:@"Close"
                                                                                         style:UIBarButtonItemStylePlain
                                                                                        target:self
                                                                                        action:@selector(dismissRequestListModal:)]];
            }
        }
        @catch (NSException *exception) {
            NSLog(@"exception: %@",exception);
        }
    }
}
```

**Comment by markst** [comment] 2016-02-26 04:32
but turns out this is actually resolved now:
![simulator screen shot 26 feb 2016 15 32 10](https://cloud.githubusercontent.com/assets/274318/13343173/2a57238a-dc9e-11e5-8927-bba7f6501439.png)
