### ISSUE TITLE
Memory leaks when presenting attachments controller from the RequestUI controller

### ISSUE THREAD

**Issue by D-Link13** [zendesk/zendesk_sdk_ios#450] opened 2018-10-15 14:53 UTC
- SDK version: 2.2.0
- Xcode version: 10.0 (10A255)
- iOS or Simulator: iPhone 7
- iOS Version: 12.0.1
- Swift version: 4.1

Steps to Reproduce:

1. present RequestUI controller
2. hit an attachment button
3. dissmiss RequestUI controller
4. repeat several times steps 1-3, while reviewing the Debug navigator... you will see that ram is starting to overfill

Looks like you are holding a strong pointer to the Attachments controller so he is not going out of memory while dismissing RequestUI controller. Also checkout your blocks/closures, they also can hold a strong pointers. But this is just a predictions, you should investigate this by yourself. Good luck🍀

**Comment by RonanMcH** [comment] 2018-10-16 08:31
Hi @D-Link13 ,
Thanks for the information. We'll have a look into this memory leak and get back to you.
Ronan.

**Comment by tecknut** [comment] 2018-10-22 12:55
Hi @D-Link13, 

Ronan investigated this and was unable to reproduce the leak. 

- Have you any specific configuration code which you can share?  
- Did you use Instruments to profile this? 

Thanks, 
Alan

**Comment by HamstringAssassin** [comment] 2018-11-08 13:11
Hi @D-Link13, 

im going to tentatively close this issue. If you do have any more info for us, feel free to re-open or get in contact. 

Cheers, 
Al

**Closed by HamstringAssassin** 2018-11-08 13:11 UTC
